import { ServiceContent, NavItem, CaseStudy, ReviewItem, SpokeService } from './types';

export const SOCIAL_LINKS = {
  linkedin: 'https://www.linkedin.com/in/zechariah-tokar-167b7672/',
  twitter: 'https://x.com/ZackTokar',
  youtube: 'https://www.youtube.com/@Zechariah_T',
  reddit: 'https://www.reddit.com/r/SEO_Israel/',
  calendly: 'https://calendly.com/zack-tokar/consultation',
  email: 'zechariah@israelseofreelancer.com',
};

export const NAV_ITEMS: NavItem[] = [
  { label: 'Services', path: '/seo-services-israel' },
  { label: 'Reviews', path: '/reviews-results' },
  { label: 'About', path: '/about' },
  { label: 'Blog', path: '/blog' },
];

export const PRICING_SUMMARY = {
  hourly: '$75-$100/hr',
  consult: '$75-$100/hr',
  services: 'After site review',
};

export const PROFILE_IMAGE: string | null = null;

export const MARKETPLACE_SERVICES = [
  {
    title: 'SEO writing',
    path: '/blog-content-seo',
    price: '$75-$100/hr',
    category: 'Content and authority',
    tag: 'Pages and content',
    description: 'Service pages, BOFU content, refreshes, and SEO writing that has a clear job.',
    skills: ['SEO writing', 'BOFU pages', 'Content refreshes'],
    proof: 'Service pages and BOFU content',
    visual: 'writing',
  },
  {
    title: 'SEO audit',
    path: '/technical-seo-audit',
    price: '$75-$100/hr',
    category: 'Core SEO',
    tag: 'Fast diagnosis',
    description: 'A practical audit of technical issues, Search Console data, indexation, and quick wins.',
    skills: ['Technical SEO', 'Indexing', 'Site structure'],
    proof: 'Technical review',
    visual: 'audit',
  },
  {
    title: 'SEO consult',
    path: '/seo-consult',
    price: '$75-$100/hr',
    category: 'Core SEO',
    tag: 'Quick advice',
    description: 'A focused SEO consult for questions, priorities, second opinions, and next-step clarity.',
    skills: ['Consulting', 'Priorities', 'Roadmap'],
    proof: 'Priority setting',
    visual: 'consulting',
  },
  {
    title: 'Monthly SEO',
    path: '/seo-services-israel',
    price: '$75-$100/hr',
    category: 'Core SEO',
    tag: 'Ongoing help',
    description: 'Monthly SEO support for writing, technical fixes, authority, or strategy.',
    skills: ['Monthly SEO', 'Reporting', 'Execution'],
    proof: 'Ongoing SEO help',
    visual: 'monthly',
  },
  {
    title: 'B2B SEO',
    path: '/b2b-seo-israel',
    price: '$75-$100/hr',
    category: 'Core SEO',
    tag: 'Pipeline pages',
    description: 'SEO for B2B, SaaS, and service companies that need buyer-intent traffic.',
    skills: ['B2B SEO', 'SaaS SEO', 'Use cases'],
    proof: 'B2B and SaaS SEO',
    visual: 'b2b',
  },
  {
    title: 'Shopify SEO',
    path: '/shopify-seo',
    price: '$75-$100/hr',
    category: 'Ecommerce',
    tag: 'Store visibility',
    description: 'Collection pages, product SEO, technical cleanup, and search visibility for Shopify stores.',
    skills: ['Shopify SEO', 'Collections', 'Products'],
    proof: 'Ecommerce +300% result',
    visual: 'shopify',
  },
  {
    title: 'Google Merchant Center',
    path: '/google-merchant-center-seo',
    price: '$75-$100/hr',
    category: 'Ecommerce',
    tag: 'Feed cleanup',
    description: 'Merchant Center and product feed checks for ecommerce stores that depend on Google surfaces.',
    skills: ['Merchant Center', 'Feeds', 'Shopping'],
    proof: 'Product data review',
    visual: 'merchant',
  },
  {
    title: 'Google Business Profile',
    path: '/google-business-profile-seo',
    price: '$75-$100/hr',
    category: 'Local SEO',
    tag: 'Maps and local',
    description: 'GBP cleanup, local page priorities, and Google Maps visibility for local service businesses.',
    skills: ['GBP', 'Google Maps', 'Local SEO'],
    proof: '#1 local SEO result',
    visual: 'local',
  },
  {
    title: 'Citations and directories',
    path: '/local-citations-directories',
    price: '$75-$100/hr',
    category: 'Local SEO',
    tag: 'Trust signals',
    description: 'Local citations, directories, profiles, and NAP consistency work that supports local rankings.',
    skills: ['Citations', 'Directories', 'NAP'],
    proof: 'Local trust signals',
    visual: 'citations',
  },
  {
    title: 'AI SEO / GEO',
    path: '/ai-seo-consultant-israel',
    price: '$75-$100/hr',
    category: 'AI and social search',
    tag: 'AI visibility',
    description: 'Get clearer visibility in Google, AI answers, Reddit, and brand recommendation surfaces.',
    skills: ['AI SEO', 'GEO', 'Automation'],
    proof: 'AI search visibility',
    visual: 'ai',
  },
  {
    title: 'Reddit SEO',
    path: '/reddit-seo',
    price: '$75-$100/hr',
    category: 'AI and social search',
    tag: 'Forum visibility',
    description: 'Reddit posting and visibility work for communities that influence search and AI answers.',
    skills: ['Reddit', 'LLM visibility', 'Brand mentions'],
    proof: 'AI search surface',
    visual: 'reddit',
  },
  {
    title: 'SEO social posting',
    path: '/content-marketing-for-seo',
    price: '$75-$100/hr',
    category: 'AI and social search',
    tag: 'Distribution',
    description: 'Search-aware social posts that support visibility, trust, and content distribution.',
    skills: ['Social SEO', 'Posts', 'Distribution'],
    proof: 'LinkedIn + social search',
    visual: 'social',
  },
  {
    title: 'YouTube SEO',
    path: '/youtube-seo',
    price: '$75-$100/hr',
    category: 'AI and social search',
    tag: 'Video search',
    description: 'YouTube titles, descriptions, topic strategy, and search-friendly video packaging.',
    skills: ['YouTube SEO', 'Video topics', 'Descriptions'],
    proof: 'Live SEO video library',
    visual: 'youtube',
  },
  {
    title: 'Backlinks',
    path: '/link-building-services',
    price: '$75-$100/hr',
    category: 'Content and authority',
    tag: 'Authority',
    description: 'Authority building through relevant mentions, links, profiles, and third-party surfaces.',
    skills: ['Backlinks', 'PR mentions', 'Citations'],
    proof: 'Authority building',
    visual: 'links',
  },
  {
    title: 'Programmatic SEO',
    path: '/programmatic-seo',
    price: '$75-$100/hr',
    category: 'Core SEO',
    tag: 'Scale pages',
    description: 'Template-led SEO for useful location, comparison, directory, or use-case pages.',
    skills: ['Templates', 'Internal links', 'Indexing'],
    proof: 'Page systems',
    visual: 'programmatic',
  },
  {
    title: 'Press release SEO',
    path: '/press-release-seo',
    price: '$75-$100/hr',
    category: 'Content and authority',
    tag: 'PR visibility',
    description: 'Press releases and third-party mentions that support authority, brand search, and AI visibility.',
    skills: ['PR', 'Brand search', 'Mentions'],
    proof: 'Third-party visibility',
    visual: 'pr',
  },
];

export const REVIEWS: ReviewItem[] = [
  {
    quote: 'Where do I even begin. Zechariah was one of the best people I had ever contracted out. He was able to help us yield nearly 7 figures in revenue. His out of the box thinking and attention for detail really helped.',
    name: 'Sean Littman',
    role: 'Founder @ GIVESUITE.COM',
    initial: 'S',
    linkedinVerified: true,
  },
  {
    quote: 'Within one week, our business was showing #1 on Google Maps for every target search term we cared about. He truly understands SEO and local search.',
    name: 'Yonatan Vinnik, LSW',
    role: 'Child & Family Therapist',
    initial: 'Y',
    linkedinVerified: true,
  },
  {
    quote: 'Within a couple of months, I was ranking at the top for my key searches, which honestly shocked me. I have saved a ridiculous amount of money, easily thousands of dollars.',
    name: 'Brett Sheldon, LCSW',
    role: 'CEO @ Launch Point Network',
    initial: 'B',
    linkedinVerified: true,
  },
  {
    quote: 'Extremely talented, sharp, and genuinely passionate. He is both creative and analytical, a rare combination, and quickly understands how to deliver real results.',
    name: 'Yehudah Kreitenberg',
    role: 'CBDO @ PAYIP',
    initial: 'Y',
    linkedinVerified: true,
  },
  {
    quote: 'He took the time to understand my business and explained strategy in a way that was practical and easy to follow. Very knowledgeable and honest.',
    name: 'Menachem Encaoua',
    role: 'Entrepreneur @ Turning Ideas Into Businesses',
    initial: 'M',
    linkedinVerified: true,
  },
  {
    quote: "He doesn't just tick boxes. He cares. SEO isn't about doing all the right things, it's about bringing the right people to your site.",
    name: 'Rivka Neumann',
    role: 'Founder @ FLYHOST.ME',
    initial: 'R',
    linkedinVerified: true,
  },
];

export const SERVICE_SPOKES: SpokeService[] = [
  {
    slug: 'shopify-seo',
    title: 'Shopify SEO for stores that need cleaner collection and product visibility.',
    seoTitle: 'Shopify SEO Consultant | Ecommerce SEO at $75-$100/hr',
    metaDescription: 'Shopify SEO help for collections, product pages, technical cleanup, Google Search Console, and ecommerce search visibility.',
    eyebrow: 'Shopify SEO',
    parentPath: '/seo-services-israel',
    parentLabel: 'SEO services',
    bestFor: 'Shopify stores with products that should already be showing up in Google.',
    intro: 'Shopify SEO usually fails in the small places: thin collection pages, duplicate product signals, weak internal links, missing schema, and search terms that never match how buyers shop.',
    handles: ['Collection page cleanup', 'Product title and metadata review', 'Indexation and canonical checks', 'Internal links between products and collections', 'Search Console opportunity review'],
    proof: 'ZStander grew Google sales after collection-page and shopping-support work around seasonal demand.',
    related: ['Google Merchant Center SEO', 'SEO writing', 'Technical SEO audit'],
    cta: 'Send the Shopify store and the product category you care about most.',
  },
  {
    slug: 'google-merchant-center-seo',
    title: 'Google Merchant Center SEO and feed cleanup for ecommerce stores.',
    seoTitle: 'Google Merchant Center SEO | Feed Cleanup and Shopping Visibility',
    metaDescription: 'Google Merchant Center SEO and product feed cleanup for ecommerce stores that depend on Google Shopping and organic product visibility.',
    eyebrow: 'Google Merchant Center SEO',
    parentPath: '/seo-services-israel',
    parentLabel: 'SEO services',
    bestFor: 'Stores where product data, feeds, or Google surfaces are limiting visibility.',
    intro: 'Merchant Center work is not only ads. Product titles, feed fields, category mapping, landing page consistency, and policy issues can all affect how products appear across Google.',
    handles: ['Feed field review', 'Product title cleanup', 'Landing page consistency checks', 'Shopping and organic product visibility review', 'Merchant Center issue prioritization'],
    proof: 'Ecommerce SEO works best when product pages, collections, and Google product data all tell the same story.',
    related: ['Shopify SEO', 'Technical SEO audit', 'SEO services'],
    cta: 'Send the store URL and tell me what Merchant Center issue or product category is most important.',
  },
  {
    slug: 'google-business-profile-seo',
    title: 'Google Business Profile and local SEO for service businesses.',
    seoTitle: 'Google Business Profile SEO | Local SEO Consultant',
    metaDescription: 'Google Business Profile SEO for local service businesses, Maps visibility, local pages, reviews, and search consistency.',
    eyebrow: 'Google Business Profile SEO',
    parentPath: '/seo-services-israel',
    parentLabel: 'SEO services',
    bestFor: 'Local businesses that need better Maps visibility and clearer local search signals.',
    intro: 'Local SEO is usually a trust problem. Google needs a clean business profile, consistent citations, useful local pages, and enough proof to understand where and why you should show.',
    handles: ['GBP category and service review', 'Local page recommendations', 'Review and photo priorities', 'NAP consistency checks', 'Google Maps search review'],
    proof: 'Yonatan Vinnik reported #1 Google Maps visibility for the target local searches after local SEO work.',
    related: ['Local citations / directories', 'SEO services', 'Technical SEO audit'],
    cta: 'Send the business profile and the city or service searches you want to improve.',
  },
  {
    slug: 'local-citations-directories',
    title: 'Local citations and directories that support local search trust.',
    seoTitle: 'Local Citations and Directory SEO | NAP Cleanup',
    metaDescription: 'Local citation and directory SEO for NAP consistency, business profiles, authority signals, and local search visibility.',
    eyebrow: 'Citations and directories',
    parentPath: '/link-building-services',
    parentLabel: 'Link building services',
    bestFor: 'Local businesses with messy listings, weak local authority, or inconsistent business details.',
    intro: 'Citations are not glamorous, but bad listings confuse local search. The goal is not to submit to every directory. The goal is to clean the important ones and build signals that make the business easier to trust.',
    handles: ['NAP consistency review', 'Priority directory selection', 'Profile cleanup', 'Local authority opportunities', 'Citation gap review'],
    proof: 'Local SEO gains often come from simple trust signals combined with stronger local pages and reviews.',
    related: ['Google Business Profile SEO', 'Backlinks', 'SEO services'],
    cta: 'Send the business name, website, and main city or service area.',
  },
  {
    slug: 'reddit-seo',
    title: 'Reddit SEO for brand visibility, AI search, and buyer research.',
    seoTitle: 'Reddit SEO Consultant | Reddit Visibility and AI Search',
    metaDescription: 'Reddit SEO help for search visibility, brand mentions, buyer research, AI visibility, and useful discussion-led content.',
    eyebrow: 'Reddit SEO',
    parentPath: '/ai-seo-consultant-israel',
    parentLabel: 'AI SEO',
    bestFor: 'Brands where Reddit threads influence Google results, AI answers, or buyer trust.',
    intro: 'Reddit now shows up in Google results and AI research paths. The useful play is not spam. It is finding the right discussions, understanding objections, and building content or participation that answers real buyer questions.',
    handles: ['Relevant subreddit research', 'Buyer-objection mapping', 'Reddit SERP review', 'Discussion-led content ideas', 'Brand mention opportunities'],
    proof: 'The current SEO system already uses Reddit research for content gaps, AI visibility, and search-aware distribution.',
    related: ['AI SEO / GEO', 'SEO social posting', 'Content marketing for SEO'],
    cta: 'Send the brand and the topic where Reddit is already influencing buyers.',
  },
  {
    slug: 'youtube-seo',
    title: 'YouTube SEO for videos that need search-friendly packaging.',
    seoTitle: 'YouTube SEO Consultant | Video Titles, Topics, and Descriptions',
    metaDescription: 'YouTube SEO help for video topics, titles, descriptions, search intent, internal links, and Google video visibility.',
    eyebrow: 'YouTube SEO',
    parentPath: '/content-marketing-for-seo',
    parentLabel: 'Content marketing for SEO',
    bestFor: 'Channels or businesses that already make videos but need clearer search packaging.',
    intro: 'YouTube SEO starts before upload. The topic, title, thumbnail promise, description, chapters, and page support all need to match what people search and what the video actually answers.',
    handles: ['Video topic research', 'Title and description cleanup', 'Chapter and entity recommendations', 'Google video SERP checks', 'Blog or service-page support ideas'],
    proof: 'Zechariah publishes SEO videos and uses YouTube as part of the broader search and AI visibility system.',
    related: ['SEO writing', 'AI SEO / GEO', 'SEO social posting'],
    cta: 'Send the channel or video list and the topic you want to be found for.',
  },
  {
    slug: 'programmatic-seo',
    title: 'Programmatic SEO for useful page systems, not thin page spam.',
    seoTitle: 'Programmatic SEO Consultant | Template SEO and Scalable Pages',
    metaDescription: 'Programmatic SEO consulting for useful template pages, internal linking, indexation, data structure, and scalable search pages.',
    eyebrow: 'Programmatic SEO',
    parentPath: '/ai-seo-consultant-israel',
    parentLabel: 'AI SEO',
    bestFor: 'Companies with real data, locations, categories, products, integrations, or use cases that can support useful page templates.',
    intro: 'Programmatic SEO only works when the page type deserves to exist. Thin generated pages create risk. Useful templates answer a repeated buyer question with specific data, internal links, and a clear next step.',
    handles: ['Page-template strategy', 'Indexation risk review', 'Internal link architecture', 'Data field recommendations', 'Pilot page batch planning'],
    proof: 'The same authority architecture behind B2B and local SEO applies to scalable page systems.',
    related: ['Technical SEO audit', 'AI SEO / GEO', 'B2B SEO'],
    cta: 'Send the idea, data source, and one example page you want to scale.',
  },
  {
    slug: 'seo-consult',
    title: 'SEO consults for clear priorities before you spend more.',
    seoTitle: 'SEO Consult | Freelance SEO Consultant at $75-$100/hr',
    metaDescription: 'SEO consults for audits, strategy, second opinions, content plans, technical questions, and clear SEO priorities.',
    eyebrow: 'SEO consult',
    parentPath: '/seoconsulting',
    parentLabel: 'SEO consulting',
    bestFor: 'Founders and marketers who need direction before committing to a bigger SEO project.',
    intro: 'A consult is useful when you are stuck between too many SEO tasks. The goal is to decide what matters first, what can wait, and what is probably not worth paying for right now.',
    handles: ['Quick site review', 'GSC and keyword priority review', 'Content or technical second opinion', '90-day priority outline', 'Vendor or freelancer scope review'],
    proof: 'Clients repeatedly mention clear explanations, practical strategy, and honest prioritization in reviews.',
    related: ['Technical SEO audit', 'B2B SEO', 'SEO services'],
    cta: 'Send the site and the decision you are trying to make.',
  },
  {
    slug: 'press-release-seo',
    title: 'Press release SEO for brand search, authority, and third-party visibility.',
    seoTitle: 'Press Release SEO | PR Mentions and Authority Building',
    metaDescription: 'Press release SEO help for brand search, authority building, third-party mentions, AI visibility, and reputation support.',
    eyebrow: 'Press release SEO',
    parentPath: '/link-building-services',
    parentLabel: 'Link building services',
    bestFor: 'Brands that need credible third-party surfaces to support search, reputation, and AI visibility.',
    intro: 'A press release should not be random noise. It should support a real entity signal: who you are, what you do, why the update matters, and where buyers or AI systems can verify the brand.',
    handles: ['News angle review', 'Entity and brand wording', 'Distribution fit review', 'Anchor and mention planning', 'Follow-up authority opportunities'],
    proof: 'Zechariah has public third-party mentions around SEO consulting, AI search, Wharton background, and Semrush certifications.',
    related: ['Backlinks', 'AI SEO / GEO', 'SEO reputation management'],
    cta: 'Send the announcement idea and the business goal behind it.',
  },
  {
    slug: 'blog-content-seo',
    title: 'Blog content SEO for articles that support rankings and buyers.',
    seoTitle: 'Blog Content SEO | SEO Writing and Content Refreshes',
    metaDescription: 'Blog content SEO help for article strategy, content refreshes, BOFU posts, internal links, and search-focused writing.',
    eyebrow: 'Blog content SEO',
    parentPath: '/content-marketing-for-seo',
    parentLabel: 'Content marketing for SEO',
    bestFor: 'Companies with blog content that should support service pages, comparisons, and buyer research.',
    intro: 'Blog SEO should not mean publishing more words. A useful article answers a real search problem, supports a money page, and gives buyers a reason to trust the business before they contact you.',
    handles: ['Content refresh review', 'BOFU article planning', 'Internal link recommendations', 'SERP and Reddit research', 'Title and meta cleanup'],
    proof: 'The current site already has indexed B2B, AI search, cybersecurity, SaaS, and content marketing articles.',
    related: ['SEO writing', 'B2B SEO', 'AI SEO / GEO'],
    cta: 'Send the blog URL or keyword cluster you want to improve.',
  },
];

const DATA_ECOMMERCE = [
  { date: '1', clicks: 120, impressions: 4000 },
  { date: '2', clicks: 180, impressions: 5500 },
  { date: '3', clicks: 250, impressions: 8000 },
  { date: '4', clicks: 400, impressions: 12000 },
  { date: '5', clicks: 800, impressions: 25000 },
  { date: '6', clicks: 1200, impressions: 45000 },
];

const DATA_LOCAL = [
  { date: '1', clicks: 20, impressions: 500 },
  { date: '2', clicks: 45, impressions: 1200 },
  { date: '3', clicks: 90, impressions: 2800 },
  { date: '4', clicks: 150, impressions: 4000 },
  { date: '5', clicks: 210, impressions: 5500 },
  { date: '6', clicks: 300, impressions: 8000 },
];

const DATA_B2B = [
  { date: '1', clicks: 10, impressions: 1000 },
  { date: '2', clicks: 25, impressions: 2500 },
  { date: '3', clicks: 40, impressions: 3800 },
  { date: '4', clicks: 85, impressions: 6000 },
  { date: '5', clicks: 140, impressions: 9000 },
  { date: '6', clicks: 220, impressions: 15000 },
];

export const CASE_STUDIES: CaseStudy[] = [
  {
    client: 'ZStander',
    metric: '+300%',
    context: 'Increase in Google Sales',
    industry: 'Ecommerce',
    market: 'United States',
    description: 'Optimized collection pages and targeted Google Shopping support around seasonal demand.',
    icon: 'trending_up',
    graphData: DATA_ECOMMERCE,
  },
  {
    client: 'The Behfar Team',
    metric: '#1',
    context: 'Midwood Brooklyn Real Estate',
    industry: 'Real estate',
    market: 'United States',
    description: 'Built local search visibility around high-intent neighborhood real estate searches.',
    icon: 'emoji_events',
    graphData: DATA_LOCAL,
  },
  {
    client: 'North Star Ranch',
    metric: '10+',
    context: 'Leads per month',
    industry: 'Hospitality',
    market: 'United States',
    description: 'Found a micro-wedding keyword gap and built organic visibility without ad spend.',
    icon: 'groups',
    graphData: DATA_B2B,
  },
];

const baseFaqs = [
  {
    question: 'What is the starting price?',
    answer: 'SEO work is quoted by expected hours at $75-$100/hr. Final pricing depends on service type, site size, competition, and whether the work is writing, audits, backlinks, automation, consulting, or ongoing SEO.',
  },
  {
    question: 'Do you work only with Israeli companies?',
    answer: 'No. Zechariah is based in Israel but mainly works with companies targeting English-speaking markets, especially the United States and international buyers.',
  },
];

export const SERVICE_DATA: Record<string, ServiceContent> = {
  services: {
    id: 'seo-services',
    slug: 'seo-services-israel',
    title: 'SEO services in Israel, priced like a freelancer menu.',
    seoTitle: 'SEO Services Israel | Freelance SEO Services at $75-$100/hr',
    metaDescription: 'Hire Zechariah Tokar for SEO writing, audits, AI SEO, backlinks, technical SEO, B2B SEO, and monthly SEO services by hourly quote.',
    subtitle: 'SEO Services Israel',
    primaryKeyword: 'SEO services Israel',
    priceFrom: '$75-$100/hr',
    timeline: '1 week to monthly',
    bestFor: 'Businesses that know the SEO service they need and want a clear starting point.',
    description: 'Choose the SEO help you need without sitting through a vague agency pitch. Most work is quoted by expected hours at $75-$100/hr.',
    deliverables: ['SEO writing', 'Technical SEO audit', 'Monthly SEO support', 'Shopify SEO', 'Google Merchant Center', 'Google Business Profile', 'Reddit SEO', 'YouTube SEO'],
    relatedServices: ['SEO writing', 'Audits', 'B2B SEO', 'AI SEO', 'Backlinks'],
    ugcIntro: {
      what: 'A clear menu of freelance SEO services, from one-off writing or audits to ongoing monthly support.',
      why: 'Most buyers want to know what they can hire for, what it starts at, and whether the person can actually do the work.',
      how: 'You send the site and goal. I tell you the best service fit, price range, and first practical step.',
    },
    results: [
      { label: 'Pricing', value: '$75-$100/hr' },
      { label: 'Currency', value: 'USD' },
      { label: 'Work model', value: 'Direct' },
    ],
    caseStudyHighlight: CASE_STUDIES[0],
    process: {
      title: 'How hiring works',
      steps: ['Pick the service area', 'Send the site and goal', 'Get a clear scope', 'Start with the highest-impact work'],
    },
    tools: ['Google Search Console', 'GA4', 'Screaming Frog', 'Reddit research', 'AI workflow tools'],
    pricing: { audit: 'Quoted hourly', management: 'Quoted hourly' },
    features: ['One-off and monthly SEO options', 'Direct senior work', 'Pricing in USD', 'No agency handoff'],
    whyMe: ['Direct access to the person doing the thinking', 'Practical SEO tied to pages, rankings, leads, and sales context'],
    cta: 'Send your site and the service you are considering. I will reply with the cleanest first step.',
    faqs: baseFaqs,
  },
  freelance: {
    id: 'freelance-seo',
    slug: 'freelance-seo-israel',
    title: 'Freelance SEO in Israel for companies that want direct help.',
    seoTitle: 'Freelance SEO Israel | Hire Zechariah Tokar',
    metaDescription: 'Hire Zechariah Tokar for freelance SEO in Israel. SEO work quoted at $75-$100/hr after a quick project review.',
    subtitle: 'Freelance SEO Israel',
    primaryKeyword: 'freelance SEO Israel',
    priceFrom: '$75-$100/hr',
    timeline: 'Project or monthly',
    bestFor: 'Founders, marketers, and service businesses that want one accountable SEO operator.',
    description: 'Hire me for practical SEO work without agency layers. I help with writing, audits, technical cleanup, content planning, AI visibility, backlinks, and monthly SEO.',
    deliverables: ['SEO audit', 'Keyword and GSC review', 'Service page rewrites', 'Technical fixes', 'Content strategy', 'Monthly SEO support'],
    relatedServices: ['SEO services', 'B2B SEO', 'Technical SEO', 'AI SEO'],
    ugcIntro: {
      what: 'Hands-on SEO from a freelancer based in Israel, focused on English-speaking markets.',
      why: 'You get faster decisions, clearer priorities, and fewer layers between strategy and execution.',
      how: 'I look at the site, rankings, search intent, and offer, then start with the pages closest to money.',
    },
    results: [
      { label: 'Hourly rate', value: '$75-$100/hr' },
      { label: 'Work style', value: 'Direct' },
      { label: 'Market focus', value: 'US/global' },
    ],
    caseStudyHighlight: CASE_STUDIES[1],
    process: {
      title: 'Freelance SEO process',
      steps: ['Audit what already exists', 'Find the terms closest to buyers', 'Fix weak pages first', 'Build the next service or content pages'],
    },
    tools: ['Google Search Console', 'GA4', 'Screaming Frog', 'Keywords Everywhere', 'Reddit'],
    pricing: { audit: 'Quoted hourly', management: 'Quoted hourly' },
    features: ['SEO writing', 'Technical SEO', 'Monthly SEO', 'AI SEO visibility', 'Backlink strategy'],
    whyMe: ['No account manager relay', 'Plain explanations', 'Search work tied to actual business goals'],
    cta: 'Send the site and tell me what you want SEO to fix first.',
    faqs: baseFaqs,
    deepDive: [
      {
        title: 'What I check first',
        body: "I start with the pages already closest to revenue: service pages, comparison pages, local pages, and any content that has impressions but weak clicks. From there, I check Search Console, crawl basics, titles, page intent, and whether the offer is clear enough for a buyer who doesn't know me yet.",
      },
      {
        title: 'Why direct freelance SEO can work better',
        body: "A lot of SEO slows down because strategy and execution get separated. I keep the first pass direct. If the page needs writing, I write. If the problem is indexing or internal links, I map the fix. If the site needs authority, I point the effort at the pages most likely to bring leads.",
      },
    ],
  },
  b2b: {
    id: 'b2b-seo',
    slug: 'b2b-seo-israel',
    title: 'B2B SEO in Israel for US-facing companies.',
    seoTitle: 'B2B SEO Israel | SaaS and Service SEO Consultant',
    metaDescription: 'B2B SEO in Israel for SaaS, service, and international companies targeting US and English-speaking buyers.',
    subtitle: 'B2B SEO Israel',
    primaryKeyword: 'B2B SEO Israel',
    priceFrom: '$75-$100/hr',
    timeline: 'Monthly or project',
    bestFor: 'B2B, SaaS, service, and tech companies that need buyer-intent pages.',
    description: 'B2B SEO works when it gets close to pipeline: service pages, use cases, comparisons, pricing intent, and content buyers read before they contact you.',
    deliverables: ['B2B keyword map', 'Service page strategy', 'Use case pages', 'Comparison pages', 'Content refreshes', 'Internal linking'],
    relatedServices: ['SEO consulting', 'Content SEO', 'AI SEO'],
    ugcIntro: {
      what: 'SEO for B2B companies that care about qualified leads more than traffic volume.',
      why: 'B2B buyers research before they talk to sales. If the pages are vague, rankings do not help much.',
      how: 'I map the buyer searches, sharpen the offer pages, and build BOFU content around real decision points.',
    },
    results: [
      { label: 'B2B page impressions', value: '1,688' },
      { label: 'Keyword cluster', value: 'B2B SEO Israel' },
      { label: 'Pricing', value: '$75-$100/hr' },
    ],
    caseStudyHighlight: CASE_STUDIES[2],
    process: {
      title: 'B2B SEO process',
      steps: ['Map buyer intent', 'Prioritize money pages', 'Rewrite unclear offers', 'Build BOFU pages', 'Track search and lead signals'],
    },
    tools: ['Google Search Console', 'GA4', 'LinkedIn', 'Reddit research', 'AI search checks'],
    pricing: { audit: 'Quoted hourly', management: 'Quoted hourly' },
    features: ['Pipeline-focused SEO', 'BOFU pages', 'SaaS and service positioning', 'AI-search visibility checks'],
    whyMe: ['I focus on pages that help buyers choose', 'I do not treat B2B SEO as generic blogging'],
    cta: 'Send your B2B site and I will identify the pages closest to revenue.',
    faqs: baseFaqs,
    deepDive: [
      {
        title: 'What I build for B2B companies',
        body: "B2B SEO is not just blog publishing. I look for the searches that happen before someone books a demo, asks for pricing, compares vendors, or tries to understand whether your company fits their market. That usually means service pages, use cases, comparison pages, integrations, and content that sales can actually use.",
      },
      {
        title: 'Where the information gain comes from',
        body: "Most B2B SEO pages talk about traffic. I care more about retrieval and buyer memory. If Google or an AI answer needs to understand what you do, the page has to name the buyer, the use case, the market, and the proof. That is why I use GSC data, SERP checks, Reddit language, LinkedIn positioning, and internal links together.",
      },
    ],
  },
  consultant: {
    id: 'seo-consulting',
    slug: 'seoconsulting',
    title: 'SEO consultant in Israel for clear strategy and priorities.',
    seoTitle: 'SEO Consultant Israel | Strategy, Audits, and Roadmaps',
    metaDescription: 'SEO consultant in Israel for audits, strategy, roadmaps, technical SEO, content planning, and AI visibility.',
    subtitle: 'SEO Consultant Israel',
    primaryKeyword: 'SEO consultant Israel',
    priceFrom: '$75-$100/hr',
    timeline: 'Audit or advisory',
    bestFor: 'Teams that can execute but need sharper SEO direction.',
    description: 'Use consulting when you need the strategy, diagnosis, and roadmap, but your team will handle some or all execution.',
    deliverables: ['SEO audit', '90-day roadmap', 'Keyword priorities', 'Content brief review', 'Technical review', 'Monthly advisory'],
    relatedServices: ['Technical SEO audit', 'B2B SEO', 'Content SEO'],
    ugcIntro: {
      what: 'Senior SEO direction without committing to a large monthly package.',
      why: 'Most teams do not need more tasks. They need the right order of operations.',
      how: 'I review the site, GSC, competitors, and current pages, then give clear priorities your team can act on.',
    },
    results: [
      { label: 'Pricing', value: '$75-$100/hr' },
      { label: 'Format', value: 'Roadmap' },
      { label: 'Best use', value: 'Clarity' },
    ],
    caseStudyHighlight: CASE_STUDIES[0],
    process: {
      title: 'Consulting process',
      steps: ['Review the site and GSC', 'Identify highest-leverage fixes', 'Map priority pages', 'Give a direct action plan'],
    },
    tools: ['Google Search Console', 'GA4', 'Screaming Frog', 'SERP review'],
    pricing: { audit: 'Quoted hourly', management: 'Custom advisory' },
    features: ['SEO roadmap', 'Technical and content priorities', 'Direct feedback', 'Execution guidance'],
    whyMe: ['Clear priorities instead of a bloated report', 'Useful for founders, marketers, and small teams'],
    cta: 'Send the site and I will tell you if consulting is the right fit.',
    faqs: baseFaqs,
    deepDive: [
      {
        title: 'What a consult is useful for',
        body: "A consult helps when you have too many possible SEO tasks and no clear order. I can look at the site, Search Console, current pages, and competitors, then tell you what I would fix first. Sometimes that is a technical issue. Sometimes the bigger problem is that the page does not say anything useful enough to win the click.",
      },
      {
        title: 'What you leave with',
        body: "The output should be practical. I do not want you stuck with a giant audit nobody opens again. You should know the first few pages to fix, what to write next, what not to waste money on, and whether you need ongoing SEO or just a small focused scope.",
      },
    ],
  },
  content: {
    id: 'content-seo',
    slug: 'content-marketing-for-seo',
    title: 'SEO writing services for pages that need to rank and sell.',
    seoTitle: 'SEO Writing Services | Content Marketing for SEO',
    metaDescription: 'SEO writing services for BOFU pages, service pages, content refreshes, SEO briefs, and search-focused content by hourly quote.',
    subtitle: 'SEO Writing Services',
    primaryKeyword: 'SEO writing services',
    priceFrom: '$75-$100/hr',
    timeline: 'Per page or batch',
    bestFor: 'Companies that need pages with search intent, proof, and a conversion path.',
    description: 'SEO writing is not blog volume. I write or rebuild pages around buyer intent, search language, proof, and a clear next step.',
    deliverables: ['Service pages', 'BOFU articles', 'Content refreshes', 'SEO briefs', 'Internal link suggestions', 'Title and meta updates'],
    relatedServices: ['B2B SEO', 'SEO services', 'AI SEO'],
    ugcIntro: {
      what: 'SEO writing for service pages, BOFU content, and refreshes.',
      why: 'A page can rank and still fail if the offer is unclear or the copy does not help someone choose.',
      how: 'I map the search intent, compare the SERP, add useful information gain, and write the page around the decision.',
    },
    results: [
      { label: 'Pricing', value: '$75-$100/hr' },
      { label: 'Format', value: 'Page work' },
      { label: 'Focus', value: 'BOFU' },
    ],
    caseStudyHighlight: CASE_STUDIES[2],
    process: {
      title: 'SEO writing process',
      steps: ['Check the query and SERP', 'Choose the page angle', 'Write for clarity and conversion', 'Add title, meta, and links'],
    },
    tools: ['Google Search Console', 'SERP research', 'Reddit research', 'AI-assisted outlining'],
    pricing: { audit: 'Quoted hourly', management: 'Custom batches' },
    features: ['BOFU pages', 'Service pages', 'Refreshes', 'SEO briefs', 'Conversion-focused copy'],
    whyMe: ['I write for buyers, not just keyword density', 'Pages stay clear, short, and useful'],
    cta: 'Send the page or keyword you want to improve.',
    faqs: baseFaqs,
    deepDive: [
      {
        title: 'How I decide what to write',
        body: "I do not start with a content calendar. I start with the search result, the page that should make money, and the questions buyers ask before they trust the offer. A good SEO article should support a service page, answer a real decision, or give Google a clearer reason to understand the brand.",
      },
      {
        title: 'What makes the copy different',
        body: "Most SEO writing sounds interchangeable. I try to put the useful difference near the top: the market, the buyer, the proof, the tools, and the reason this page should exist. That is also how I think about AI search. The page needs enough specific information for a model or a buyer to retrieve the brand for the right reason.",
      },
    ],
  },
  ai: {
    id: 'ai-seo',
    slug: 'ai-seo-consultant-israel',
    title: 'AI SEO consultant in Israel for Google and AI visibility.',
    seoTitle: 'AI SEO Consultant Israel | GEO and AI Visibility',
    metaDescription: 'AI SEO consultant in Israel for GEO, AI visibility, ChatGPT and Perplexity recommendation checks, and automation-assisted SEO.',
    subtitle: 'AI SEO Consultant Israel',
    primaryKeyword: 'AI SEO freelancer',
    priceFrom: '$75-$100/hr',
    timeline: 'Audit or monthly',
    bestFor: 'Brands that want to understand how AI search changes discovery.',
    description: 'AI SEO is not mass-producing generic content. It is making the brand clearer across Google, AI answers, Reddit, reviews, and third-party surfaces.',
    deliverables: ['AI visibility check', 'Brand retrieval review', 'GEO content plan', 'Reddit and forum surface review', 'Automation workflow ideas', 'Entity cleanup'],
    relatedServices: ['SEO consulting', 'Content SEO', 'Backlinks'],
    ugcIntro: {
      what: 'A practical look at how your brand appears in AI-assisted search and recommendation journeys.',
      why: 'Buyers increasingly ask AI who to hire, then Google the names they get back.',
      how: 'I test visibility, find weak entity signals, and build pages or third-party mentions that make the brand easier to retrieve.',
    },
    results: [
      { label: 'Pricing', value: '$75-$100/hr' },
      { label: 'Surfaces', value: 'Google + AI' },
      { label: 'Focus', value: 'Retrieval' },
    ],
    caseStudyHighlight: CASE_STUDIES[0],
    process: {
      title: 'AI SEO process',
      steps: ['Check current AI visibility', 'Map missing entity signals', 'Find trusted surfaces', 'Build content and mentions that clarify the brand'],
    },
    tools: ['ChatGPT checks', 'Perplexity checks', 'Google Search Console', 'Reddit research', 'Automation tools'],
    pricing: { audit: 'Quoted hourly', management: 'Quoted hourly' },
    features: ['GEO visibility', 'AI recommendation checks', 'Brand/entity clarity', 'Automation-assisted SEO'],
    whyMe: ['I treat AI SEO as brand retrieval, not spam content', 'I connect AI visibility with regular Google visibility'],
    cta: 'Send the brand and site. I will check what AI and Google understand about it.',
    faqs: baseFaqs,
    deepDive: [
      {
        title: 'What I mean by AI SEO',
        body: "AI SEO is not publishing a pile of generated posts. I look at whether Google, ChatGPT, Perplexity, Reddit, YouTube, and third-party pages describe the brand clearly. If the brand is hard to understand, it is hard to recommend. That is the problem I try to fix.",
      },
      {
        title: 'What I check',
        body: "I test what AI systems say about the company, then compare that with Google results, Search Console data, internal pages, and outside mentions. The work can include better service pages, clearer entity signals, Reddit research, YouTube packaging, backlinks, or simple cleanup of confusing brand language.",
      },
    ],
  },
  technical: {
    id: 'technical-seo-audit',
    slug: 'technical-seo-audit',
    title: 'Technical SEO audit for crawl, indexation, and GSC cleanup.',
    seoTitle: 'Technical SEO Audit | GSC, Indexing, and Site Fixes',
    metaDescription: 'Technical SEO audit for Google Search Console, indexing, crawl issues, site structure, metadata, schema, and practical quick wins by hourly quote.',
    subtitle: 'Technical SEO Audit',
    primaryKeyword: 'technical SEO audit',
    priceFrom: '$75-$100/hr',
    timeline: 'Usually 1 week',
    bestFor: 'Sites with ranking, indexing, traffic, or messy technical issues.',
    description: 'A technical audit should tell you what to fix first, not bury you in a giant PDF. I focus on crawlability, indexation, metadata, page structure, and quick wins.',
    deliverables: ['GSC review', 'Indexing checks', 'Metadata issues', 'Site structure review', 'Schema recommendations', 'Priority fix list'],
    relatedServices: ['SEO consulting', 'SEO services', 'B2B SEO'],
    ugcIntro: {
      what: 'A practical audit of the technical issues stopping pages from performing.',
      why: 'Weak indexation, duplicate signals, poor structure, and unclear metadata can waste good content.',
      how: 'I check GSC, crawl the site, review priority templates, and return a short fix list in the right order.',
    },
    results: [
      { label: 'Pricing', value: '$75-$100/hr' },
      { label: 'Output', value: 'Fix list' },
      { label: 'Focus', value: 'GSC' },
    ],
    caseStudyHighlight: CASE_STUDIES[1],
    process: {
      title: 'Audit process',
      steps: ['Review GSC', 'Crawl the site', 'Check indexation and templates', 'Prioritize fixes by impact'],
    },
    tools: ['Google Search Console', 'Screaming Frog', 'GA4', 'PageSpeed Insights'],
    pricing: { audit: 'Quoted hourly', management: 'Custom fixes' },
    features: ['GSC cleanup', 'Indexation checks', 'Metadata review', 'Technical priority list'],
    whyMe: ['Short practical recommendations', 'Focus on fixes that affect search visibility'],
    cta: 'Send your site and I will check where technical SEO is blocking growth.',
    faqs: baseFaqs,
  },
  links: {
    id: 'link-building',
    slug: 'link-building-services',
    title: 'Link building services for authority that supports real SEO.',
    seoTitle: 'Link Building Services | SEO Backlinks and Authority Building',
    metaDescription: 'Link building services for SEO backlinks, authority building, mentions, citations, and third-party visibility by hourly quote.',
    subtitle: 'Link Building Services',
    primaryKeyword: 'SEO backlinks',
    priceFrom: '$75-$100/hr',
    timeline: 'Monthly or project',
    bestFor: 'Sites that already have decent pages but need more authority and trust signals.',
    description: 'Backlinks should support a real search strategy. I focus on relevant mentions, credible profiles, citations, and surfaces that help buyers and search engines understand the brand.',
    deliverables: ['Authority review', 'Backlink gap check', 'Citation opportunities', 'Profile cleanup', 'PR mention ideas', 'Third-party surface plan'],
    relatedServices: ['AI SEO', 'SEO consulting', 'B2B SEO'],
    ugcIntro: {
      what: 'Authority building through relevant links, mentions, profiles, and third-party surfaces.',
      why: 'A good page still needs trust. Bad links can waste money or create risk.',
      how: 'I review the current link profile, find relevant opportunities, and prioritize quality over volume.',
    },
    results: [
      { label: 'Pricing', value: '$75-$100/hr' },
      { label: 'Focus', value: 'Authority' },
      { label: 'Approach', value: 'Relevant' },
    ],
    caseStudyHighlight: CASE_STUDIES[0],
    process: {
      title: 'Authority process',
      steps: ['Review current authority', 'Compare competitors', 'Find relevant surfaces', 'Build links and mentions around priority pages'],
    },
    tools: ['Moz', 'Google Search', 'Reddit research', 'Directory review'],
    pricing: { audit: 'Quoted hourly', management: 'Quoted hourly' },
    features: ['Backlink gap review', 'Relevant citations', 'Authority planning', 'Third-party visibility'],
    whyMe: ['No link spam promises', 'Authority work tied to pages that matter'],
    cta: 'Send the page you want to strengthen.',
    faqs: baseFaqs,
  },
  reviews: {
    id: 'reviews-results',
    slug: 'reviews-results',
    title: 'SEO freelancer reviews and selected results.',
    seoTitle: 'SEO Freelancer Reviews | Zechariah Tokar Results',
    metaDescription: 'Read selected SEO freelancer reviews and results for Zechariah Tokar, including SEO wins across ecommerce, local services, and B2B.',
    subtitle: 'Reviews and Results',
    primaryKeyword: 'SEO freelancer reviews',
    priceFrom: '$75-$100/hr',
    timeline: 'Proof hub',
    bestFor: 'People who want to vet Zechariah before hiring.',
    description: 'Before you hire anyone for SEO, check what clients say and what kind of results the work has produced.',
    deliverables: ['Verified review snippets', 'Selected results', 'Service fit notes', 'Links to public profiles'],
    relatedServices: ['Freelance SEO', 'SEO services', 'B2B SEO'],
    ugcIntro: {
      what: 'A compact proof hub with reviews, selected outcomes, and public places to vet my thinking.',
      why: 'SEO is easy to overclaim. You should be able to check the person before you hire.',
      how: 'Read the review snippets, scan selected results, then use LinkedIn, YouTube, or Reddit to judge the fit.',
    },
    results: [
      { label: 'Ecommerce', value: '+300%' },
      { label: 'Local SEO', value: '#1' },
      { label: 'Pricing', value: '$75-$100/hr' },
    ],
    caseStudyHighlight: CASE_STUDIES[2],
    process: {
      title: 'How to vet me',
      steps: ['Read review snippets', 'Check selected outcomes', 'Review public thinking', 'Send the site if there is a fit'],
    },
    tools: ['LinkedIn', 'YouTube', 'Reddit', 'Google Search Console'],
    pricing: { audit: 'Quoted hourly', management: 'Quoted hourly' },
    features: ['Reviews', 'Selected results', 'Public profiles', 'Direct hire CTA'],
    whyMe: ['You can judge the proof before booking', 'The site gives you the service menu and pricing upfront'],
    cta: 'If the proof fits what you need, send the site and service area.',
    faqs: baseFaqs,
  },
};

export const SERVICES_LIST = Object.entries(SERVICE_DATA).map(([key, data]) => ({
  key,
  ...data,
}));

export const CLIENT_LOGOS = [
  { name: 'JLUXURY', style: 'font-display font-bold text-2xl tracking-widest' },
  { name: 'Whitsunday', style: 'font-display italic text-2xl' },
  { name: 'ADORNA', style: 'font-sans font-bold text-xl tracking-[0.3em] border-2 border-current px-2 py-1' },
  { name: 'Pink Orchid', style: 'font-display italic text-2xl' },
  { name: 'NORTH STAR RANCH', style: 'font-sans font-bold text-sm tracking-widest leading-tight text-center' },
];







