import { ServiceContent, NavItem, NavGroup, CaseStudy, ReviewItem, SpokeService, SupportPage } from './types';

export const SOCIAL_LINKS = {
  linkedin: 'https://www.linkedin.com/in/zechariah-tokar-167b7672/',
  twitter: 'https://x.com/ZackTokar',
  youtube: 'https://www.youtube.com/@Zechariah_T',
  reddit: 'https://www.reddit.com/r/SEO_Israel/',
  email: 'zechariah@israelseofreelancer.com',
};

export const NAV_ITEMS: NavItem[] = [
  { label: 'Services', path: '/seo-services-israel' },
  { label: 'Reviews', path: '/reviews-results' },
  { label: 'About', path: '/about' },
  { label: 'Blog', path: '/blog' },
];

// Grouped nav for the redesigned header. Every link points to an existing route.
export const NAV_MENU: NavGroup[] = [
  {
    label: 'SEO Services',
    children: [
      { label: 'All SEO Services', desc: 'See the full menu', path: '/seo-services-israel' },
      { label: 'Freelance SEO', desc: 'Hands-on SEO, senior level', path: '/freelance-seo-israel' },
      { label: 'SEO Consulting', desc: 'Strategy and a clear roadmap', path: '/seoconsulting' },
      { label: 'Technical SEO Audit', desc: 'Find what to fix first', path: '/technical-seo-audit' },
      { label: 'SEO Content Writing', desc: 'Pages that rank and convert', path: '/content-marketing-for-seo' },
      { label: 'Programmatic SEO', desc: 'Useful pages at scale', path: '/programmatic-seo' },
    ],
  },
  {
    label: 'Ecommerce & Local',
    children: [
      { label: 'Shopify SEO', desc: 'Collections and products that rank', path: '/shopify-seo' },
      { label: 'Google Merchant Center', desc: 'Fix the Shopping feed', path: '/google-merchant-center-seo' },
      { label: 'Google Business Profile', desc: 'Show up in Maps and local', path: '/google-business-profile-seo' },
      { label: 'Local Citations', desc: 'Consistent listings everywhere', path: '/local-citations-directories' },
    ],
  },
  {
    label: 'AI & Reddit',
    children: [
      { label: 'AI Search Visibility', desc: 'Get found in AI answers', path: '/ai-seo-consultant-israel' },
      { label: 'Reddit SEO', desc: 'Rank in discussions and AI', path: '/reddit-seo' },
      { label: 'Reddit Marketing', desc: 'Be recommended by real people', path: '/reddit-marketing-services' },
      { label: 'Reddit Posting Service', desc: 'Posting done the right way', path: '/reddit-posting-service' },
      { label: 'YouTube SEO', desc: 'Make videos findable', path: '/youtube-seo' },
    ],
  },
  {
    label: 'B2B & Authority',
    children: [
      { label: 'B2B SEO', desc: 'Reach decision-makers', path: '/b2b-seo-israel' },
      { label: 'Link Building', desc: 'Authority that ranks', path: '/link-building-services' },
      { label: 'Press Release SEO', desc: 'Support brand search', path: '/press-release-seo' },
      { label: 'Blog Content SEO', desc: 'Content that supports leads', path: '/blog-content-seo' },
    ],
  },
  {
    label: 'Company',
    children: [
      { label: 'Case Studies', desc: 'Real campaigns and results', path: '/case-studies' },
      { label: 'About', desc: 'Who you work with', path: '/about' },
      { label: 'Reviews & Results', desc: 'Proof and case results', path: '/reviews-results' },
      { label: 'Videos', desc: 'Watch the work', path: '/videos' },
      { label: 'Claude Skill', desc: 'Free DataIsBeautiful prompt', path: '/resources/dataisbeautiful-claude-skill' },
      { label: 'Blog', desc: 'Notes on modern search', path: '/blog' },
    ],
  },
];

// Full link map for the footer so every page is reachable (recovers internal-link authority).
export const FOOTER_COLUMNS: { heading: string; links: { label: string; path: string }[] }[] = [
  {
    heading: 'SEO Services',
    links: [
      { label: 'All SEO Services', path: '/seo-services-israel' },
      { label: 'Freelance SEO', path: '/freelance-seo-israel' },
      { label: 'SEO Consulting', path: '/seoconsulting' },
      { label: 'Technical SEO Audit', path: '/technical-seo-audit' },
      { label: 'SEO Content Writing', path: '/content-marketing-for-seo' },
      { label: 'Programmatic SEO', path: '/programmatic-seo' },
    ],
  },
  {
    heading: 'Ecommerce & Local',
    links: [
      { label: 'Shopify SEO', path: '/shopify-seo' },
      { label: 'Google Merchant Center', path: '/google-merchant-center-seo' },
      { label: 'Google Business Profile', path: '/google-business-profile-seo' },
      { label: 'Local Citations', path: '/local-citations-directories' },
    ],
  },
  {
    heading: 'AI, Reddit & Video',
    links: [
      { label: 'AI Search Visibility', path: '/ai-seo-consultant-israel' },
      { label: 'Reddit SEO', path: '/reddit-seo' },
      { label: 'Reddit Marketing', path: '/reddit-marketing-services' },
      { label: 'Reddit Posting Service', path: '/reddit-posting-service' },
      { label: 'YouTube SEO', path: '/youtube-seo' },
    ],
  },
  {
    heading: 'B2B & Authority',
    links: [
      { label: 'B2B SEO', path: '/b2b-seo-israel' },
      { label: 'Link Building', path: '/link-building-services' },
      { label: 'Press Release SEO', path: '/press-release-seo' },
      { label: 'Blog Content SEO', path: '/blog-content-seo' },
      { label: 'SEO Consult', path: '/seo-consult' },
    ],
  },
  {
    heading: 'Resources',
    links: [
      { label: 'DataIsBeautiful Claude Skill', path: '/resources/dataisbeautiful-claude-skill' },
      { label: 'Case Studies', path: '/case-studies' },
      { label: 'Reviews & Results', path: '/reviews-results' },
      { label: 'Blog', path: '/blog' },
    ],
  },
  {
    heading: 'AI Search Guides',
    links: [
      { label: 'Get cited by ChatGPT', path: '/how-to-get-cited-by-chatgpt' },
      { label: 'Rank in AI Overviews', path: '/how-to-rank-in-google-ai-overviews' },
      { label: 'Is GEO the new SEO?', path: '/is-geo-the-new-seo' },
      { label: 'What is GEO?', path: '/what-is-generative-engine-optimization' },
      { label: 'Brand mentioned in ChatGPT', path: '/how-to-get-your-brand-mentioned-in-chatgpt' },
      { label: 'What is AEO?', path: '/what-is-answer-engine-optimization' },
      { label: 'Track AI visibility', path: '/how-to-track-ai-search-visibility' },
    ],
  },
  {
    heading: 'Reddit Guides',
    links: [
      { label: 'Promote without getting banned', path: '/how-to-promote-on-reddit-without-getting-banned' },
      { label: 'Use Reddit for SEO', path: '/how-to-use-reddit-for-seo' },
      { label: 'Why Reddit ranks so high', path: '/why-does-reddit-rank-so-high-on-google' },
      { label: 'Rank a Reddit post on Google', path: '/how-to-rank-a-reddit-post-on-google' },
      { label: 'How to market on Reddit', path: '/how-to-market-on-reddit' },
    ],
  },
  {
    heading: 'Company',
    links: [
      { label: 'Case Studies', path: '/case-studies' },
      { label: 'About', path: '/about' },
      { label: 'Reviews & Results', path: '/reviews-results' },
      { label: 'Videos', path: '/videos' },
      { label: 'Freelancer vs Agency', path: '/seo-freelancer-vs-agency' },
      { label: 'Market on Reddit Safely', path: '/how-to-market-on-reddit-without-getting-banned' },
      { label: 'Find Subreddits', path: '/how-to-find-subreddits-for-marketing' },
      { label: 'Why Posts Get Removed', path: '/why-reddit-posts-get-removed' },
    ],
  },
];

// Real screenshots posted publicly (sourced from LinkedIn). Used in the homepage proof strip.
export const PROOF_ITEMS = [
  { label: 'Reddit reach', img: '/images/proof-reddit-405k.jpg', alt: 'Reddit post stats showing 405,000 views', caption_pre: 'A single Reddit post to ', caption_b: '405K views', caption_post: ' and real brand traffic.' },
  { label: 'Client post', img: '/images/proof-reddit-12k.jpg', alt: 'Reach dashboard showing 12,000 views', caption_pre: 'A client Reddit post hitting ', caption_b: '12K views', caption_post: ' in its first days.' },
  { label: 'Google lead', img: '/images/proof-google-lead.jpg', alt: 'Inbound lead message that found the client on Google', caption_pre: 'An inbound lead that ', caption_b: 'found the client on Google', caption_post: '.' },
  { label: 'Client feedback', img: '/images/proof-client-praise.jpg', alt: 'Client message praising an SEO deliverable', caption_pre: 'A client reaction to a recent ', caption_b: 'SEO deliverable', caption_post: '.' },
];

// Metric-forward testimonials for the homepage (verbatim, from /reviews-results).
export const HOME_TESTIMONIALS = [
  { result: 'Nearly 7 figures in revenue', quote: 'Zechariah was one of the best people I ever contracted. His out of the box thinking and attention to detail really helped.', name: 'Sean Littman', title: 'Founder, GiveSuite' },
  { result: '#1 on Google Maps in one week', quote: 'Within one week, our business was showing #1 on Google Maps for every target search term we cared about. I was blown away.', name: 'Yonatan Vinnik, LSW', title: 'Child & Family Therapist' },
  { result: 'Saved thousands, ranked fast', quote: 'Within a couple of months I was ranking at the top for my key searches, which honestly shocked me. Talk to Zechariah.', name: 'Brett Sheldon, LCSW', title: 'CEO, Launch Point Network' },
];

export const PROFILE_IMAGE: string | null = null;

export const MARKETPLACE_SERVICES = [
  {
    title: 'SEO writing',
    path: '/blog-content-seo',
    price: 'By consultation',
    category: 'Content and authority',
    tag: 'Pages and content',
    description: 'Service pages, BOFU content, refreshes, and SEO writing that has a clear job.',
    skills: ['SEO writing', 'BOFU pages', 'Content refreshes'],
    visual: 'writing',
  },
  {
    title: 'SEO audit',
    path: '/technical-seo-audit',
    price: 'By consultation',
    category: 'Core SEO',
    tag: 'Fast diagnosis',
    description: 'A practical audit of technical issues, Search Console data, indexation, and quick wins.',
    skills: ['Technical SEO', 'Indexing', 'Site structure'],
    visual: 'audit',
  },
  {
    title: 'SEO consult',
    path: '/seo-consult',
    price: 'By consultation',
    category: 'Core SEO',
    tag: 'Quick advice',
    description: 'A focused SEO consult for questions, priorities, second opinions, and next-step clarity.',
    skills: ['Consulting', 'Priorities', 'Roadmap'],
    visual: 'consulting',
  },
  {
    title: 'Monthly SEO',
    path: '/seo-services-israel',
    price: 'By consultation',
    category: 'Core SEO',
    tag: 'Ongoing help',
    description: 'Monthly SEO support for writing, technical fixes, authority, or strategy.',
    skills: ['Monthly SEO', 'Reporting', 'Execution'],
    visual: 'monthly',
  },
  {
    title: 'B2B SEO',
    path: '/b2b-seo-israel',
    price: 'By consultation',
    category: 'Core SEO',
    tag: 'Pipeline pages',
    description: 'SEO for B2B, SaaS, and service companies that need buyer-intent traffic.',
    skills: ['B2B SEO', 'SaaS SEO', 'Use cases'],
    visual: 'b2b',
  },
  {
    title: 'Shopify SEO',
    path: '/shopify-seo',
    price: 'By consultation',
    category: 'Ecommerce',
    tag: 'Store visibility',
    description: 'Collection pages, product SEO, technical cleanup, and search visibility for Shopify stores.',
    skills: ['Shopify SEO', 'Collections', 'Products'],
    visual: 'shopify',
  },
  {
    title: 'Google Merchant Center',
    path: '/google-merchant-center-seo',
    price: 'By consultation',
    category: 'Ecommerce',
    tag: 'Feed cleanup',
    description: 'Merchant Center and product feed checks for ecommerce stores that depend on Google surfaces.',
    skills: ['Merchant Center', 'Feeds', 'Shopping'],
    visual: 'merchant',
  },
  {
    title: 'Google Business Profile',
    path: '/google-business-profile-seo',
    price: 'By consultation',
    category: 'Local SEO',
    tag: 'Maps and local',
    description: 'GBP cleanup, local page priorities, and Google Maps visibility for local service businesses.',
    skills: ['GBP', 'Google Maps', 'Local SEO'],
    visual: 'local',
  },
  {
    title: 'Citations and directories',
    path: '/local-citations-directories',
    price: 'By consultation',
    category: 'Local SEO',
    tag: 'Trust signals',
    description: 'Local citations, directories, profiles, and NAP consistency work that supports local rankings.',
    skills: ['Citations', 'Directories', 'NAP'],
    visual: 'citations',
  },
  {
    title: 'AI SEO / GEO',
    path: '/ai-seo-consultant-israel',
    price: 'By consultation',
    category: 'AI and social search',
    tag: 'AI visibility',
    description: 'Get clearer visibility in Google, AI answers, Reddit, and brand recommendation surfaces.',
    skills: ['AI SEO', 'GEO', 'Automation'],
    visual: 'ai',
  },
  {
    title: 'Reddit SEO',
    path: '/reddit-seo',
    price: 'By consultation',
    category: 'AI and social search',
    tag: 'Forum visibility',
    description: 'Reddit posting and visibility work for communities that influence search and AI answers.',
    skills: ['Reddit', 'LLM visibility', 'Brand mentions'],
    visual: 'reddit',
  },
  {
    title: 'Reddit marketing services',
    path: '/reddit-marketing-services',
    price: 'By consultation',
    category: 'AI and social search',
    tag: 'Reddit strategy',
    description: 'Subreddit research, buyer-objection mapping, and practical Reddit campaigns that support search visibility.',
    skills: ['Reddit strategy', 'Buyer research', 'AI visibility'],
    visual: 'redditMarketing',
  },
  {
    title: 'Reddit marketing expert',
    path: '/reddit-marketing-expert',
    price: 'By consultation',
    category: 'AI and social search',
    tag: 'Specialist review',
    description: 'Focused Reddit strategy for brands that need sharper community, search, and AI visibility judgment.',
    skills: ['Reddit consult', 'Risk review', 'Search strategy'],
    visual: 'redditExpert',
  },
  {
    title: 'Reddit posting service',
    path: '/reddit-posting-service',
    price: 'By consultation',
    category: 'AI and social search',
    tag: 'Careful posting',
    description: 'Reddit post planning, writing, review, and controlled publishing without fake engagement or spam tactics.',
    skills: ['Post angles', 'Native writing', 'Review'],
    visual: 'redditPosting',
  },
  {
    title: 'SEO social posting',
    path: '/content-marketing-for-seo',
    price: 'By consultation',
    category: 'AI and social search',
    tag: 'Distribution',
    description: 'Search-aware social posts that support visibility, trust, and content distribution.',
    skills: ['Social SEO', 'Posts', 'Distribution'],
    visual: 'social',
  },
  {
    title: 'YouTube SEO',
    path: '/youtube-seo',
    price: 'By consultation',
    category: 'AI and social search',
    tag: 'Video search',
    description: 'YouTube titles, descriptions, topic strategy, and search-friendly video packaging.',
    skills: ['YouTube SEO', 'Video topics', 'Descriptions'],
    visual: 'youtube',
  },
  {
    title: 'Backlinks',
    path: '/link-building-services',
    price: 'By consultation',
    category: 'Content and authority',
    tag: 'Authority',
    description: 'Authority building through relevant mentions, links, profiles, and third-party surfaces.',
    skills: ['Backlinks', 'PR mentions', 'Citations'],
    visual: 'links',
  },
  {
    title: 'Programmatic SEO',
    path: '/programmatic-seo',
    price: 'By consultation',
    category: 'Core SEO',
    tag: 'Scale pages',
    description: 'Template-led SEO for useful location, comparison, directory, or use-case pages.',
    skills: ['Templates', 'Internal links', 'Indexing'],
    visual: 'programmatic',
  },
  {
    title: 'Press release SEO',
    path: '/press-release-seo',
    price: 'By consultation',
    category: 'Content and authority',
    tag: 'PR visibility',
    description: 'Press releases and third-party mentions that support authority, brand search, and AI visibility.',
    skills: ['PR', 'Brand search', 'Mentions'],
    visual: 'pr',
  },
];

export const REVIEWS: ReviewItem[] = [
  {
    quote: 'I recommend Zechariah for all your SEO, PPC, and marketing needs.',
    name: 'Mendel Rosenblum',
    role: 'Founder, CodeBlu Development',
    initial: 'M',
    linkedinVerified: true,
  },
  {
    quote: 'He took the time to understand my business and explained the strategy in a way that was practical and easy to follow. Very knowledgeable, honest, and genuinely helpful.',
    name: 'Menachem Encaoua',
    role: 'Entrepreneur @ Turning Ideas Into Businesses',
    initial: 'M',
    linkedinVerified: true,
  },
  {
    quote: 'Within a couple of months, I was ranking at the top for my key searches. I saved a ridiculous amount of money, easily thousands of dollars.',
    name: 'Brett Sheldon, LCSW',
    role: 'CEO, Launch Point Behavioral Health Network',
    initial: 'B',
    linkedinVerified: true,
  },
  {
    quote: 'Within one week, our business was showing up #1 on Google Maps for every target search term we cared about. I was honestly blown away.',
    name: 'Yonatan Vinnik, LSW',
    role: 'Child & Family Therapist',
    initial: 'Y',
    linkedinVerified: true,
  },
  {
    quote: 'He is extremely talented, sharp, and genuinely passionate. He is both creative and analytical, a rare combination, and quickly understands how to deliver real results.',
    name: 'Yehudah Kreitenberg',
    role: 'CBDO @ PAYIP',
    initial: 'Y',
    linkedinVerified: true,
  },
  {
    quote: 'Zechariah is remarkably knowledgeable, not to mention helpful, and accessible. Whenever I have an SEO question he is my first go-to guy.',
    name: 'Raffi Bilek',
    role: 'Couples Counselor, Speaker, and Author',
    initial: 'R',
    linkedinVerified: true,
  },
  {
    quote: 'He is super honest and cares for the businesses at the highest level. I highly recommend him for SEO projects.',
    name: 'Yochi Reich',
    role: 'E-Commerce & Marketplace Strategist',
    initial: 'Y',
    linkedinVerified: true,
  },
  {
    quote: "He doesn't just tick boxes. He cares deeply. SEO is about bringing the right people to your site, and that is exactly what he does.",
    name: 'Rivka Neumann',
    role: 'Founder @ FLYHOST.ME',
    initial: 'R',
    linkedinVerified: true,
  },
  {
    quote: 'Zechariah was one of the best people I had ever contracted out. He helped us fix our client Merchant Center account in under 10 hours, which helped us yield nearly 7 figures in revenue.',
    name: 'Sean Littman',
    role: 'Founder @ GIVESUITE.COM',
    initial: 'S',
    linkedinVerified: true,
  },
];

export const LINKEDIN_FEATURED_RESULTS = [
  {
    title: 'AI SEO audit clarity',
    metric: 'Fast, clear deliverable',
    description: 'A SaaS founder found brand-name confusion, category language issues, citation gaps, and site architecture problems from an AI SEO audit.',
    image: '/images/proof-linkedin-ai-audit.jpg',
    alt: 'LinkedIn featured image showing a client message praising an AI SEO audit deliverable',
    path: '/ai-seo-consultant-israel',
  },
  {
    title: 'Ecommerce SEO and Shopping',
    metric: 'Collection-page SEO',
    description: 'Collection-page SEO, product-page cleanup, foundational backlinks, and focused Shopping support helped improve ecommerce visibility.',
    image: '/images/proof-client-praise.jpg',
    alt: 'Client message praising an SEO deliverable',
    path: '/case-studies/zstander-shopify-seo',
  },
  {
    title: 'Local mental health SEO',
    metric: '#1 in Morristown',
    description: 'Landing-page updates, metadata, schema, competitor analysis, citations, and local content helped a therapy practice rank for key searches.',
    image: '/images/proof-linkedin-morristown.jpg',
    alt: 'LinkedIn featured image showing a local SEO result for Morristown mental health searches',
    path: '/google-business-profile-seo',
  },
  {
    title: 'AI search visibility',
    metric: '#1 on ChatGPT',
    description: 'Bing indexing, foundational links, schema, and clearer page structure helped ZStander show for a product search in ChatGPT.',
    image: '/images/proof-linkedin-chatgpt.jpg',
    alt: 'LinkedIn featured image about ranking on ChatGPT for lucite shtenders',
    path: '/case-studies/zstander-shopify-seo',
  },
];

export const SERVICE_SPOKES: SpokeService[] = [
  {
    slug: 'shopify-seo',
    title: 'Get more Shopify traffic from collection and product pages.',
    seoTitle: 'Shopify SEO Consultant | Improve Collection Pages, Product SEO, Technical Cleanup, Merchant Center Visibility and Ecommerce Search Traffic | Zechariah Tokar',
    metaDescription: 'Shopify SEO help for collections, product pages, technical cleanup, Google Search Console, and ecommerce search visibility.',
    eyebrow: 'Shopify SEO',
    parentPath: '/seo-services-israel',
    parentLabel: 'SEO services',
    bestFor: 'Shopify stores with products that should already be showing up in Google.',
    intro: 'Shopify SEO usually fails in the small places: thin collection pages, duplicate product signals, weak internal links, missing schema, and search terms that never match how buyers shop.',
    handles: ['Collection page cleanup', 'Product title and metadata review', 'Indexation and canonical checks', 'Internal links between products and collections', 'Search Console opportunity review'],
    proof: 'ZStander grew Google sales after collection-page and shopping-support work around seasonal demand.',
    related: ['Google Merchant Center SEO', 'SEO writing', 'Technical SEO audit'],
    cta: 'Send the Shopify store and the product category you care about most.',
  },
  {
    slug: 'google-merchant-center-seo',
    title: 'Fix Merchant Center issues that hold back product visibility.',
    seoTitle: 'Google Merchant Center SEO | Product Feed Cleanup, Shopping Visibility, Ecommerce Indexing, Feed Titles and Technical SEO Help | Zechariah Tokar',
    metaDescription: 'Google Merchant Center SEO and product feed cleanup for ecommerce stores that depend on Google Shopping and organic product visibility.',
    eyebrow: 'Google Merchant Center SEO',
    parentPath: '/seo-services-israel',
    parentLabel: 'SEO services',
    bestFor: 'Stores where product data, feeds, or Google surfaces are limiting visibility.',
    intro: 'Merchant Center work is not only ads. Product titles, feed fields, category mapping, landing page consistency, and policy issues can all affect how products appear across Google.',
    handles: ['Feed field review', 'Product title cleanup', 'Landing page consistency checks', 'Shopping and organic product visibility review', 'Merchant Center issue prioritization'],
    proof: 'Ecommerce SEO works best when product pages, collections, and Google product data all tell the same story.',
    related: ['Shopify SEO', 'Technical SEO audit', 'SEO services'],
    cta: 'Send the store URL and tell me what Merchant Center issue or product category is most important.',
  },
  {
    slug: 'google-business-profile-seo',
    title: 'Get found in Maps and local search by better-fit customers.',
    seoTitle: 'Google Business Profile SEO | Local SEO Consultant for Maps Visibility, Service Area Pages, Reviews, Citations and Lead Growth | Zechariah Tokar',
    metaDescription: 'Google Business Profile SEO for local service businesses, Maps visibility, local pages, reviews, and search consistency.',
    eyebrow: 'Google Business Profile SEO',
    parentPath: '/seo-services-israel',
    parentLabel: 'SEO services',
    bestFor: 'Local businesses that need better Maps visibility and clearer local search signals.',
    intro: 'Local SEO is usually a trust problem. Google needs a clean business profile, consistent citations, useful local pages, and enough proof to understand where and why you should show.',
    handles: ['GBP category and service review', 'Local page recommendations', 'Review and photo priorities', 'NAP consistency checks', 'Google Maps search review'],
    proof: 'Yonatan Vinnik reported #1 Google Maps visibility for the target local searches after local SEO work.',
    related: ['Local citations / directories', 'SEO services', 'Technical SEO audit'],
    cta: 'Send the business profile and the city or service searches you want to improve.',
  },
  {
    slug: 'local-citations-directories',
    title: 'Clean up local citations so Google can trust the business.',
    seoTitle: 'Local Citations and Directory SEO | NAP Cleanup, Business Listings, Local Authority Signals and Google Maps Support | Zechariah Tokar',
    metaDescription: 'Local citation and directory SEO for NAP consistency, business profiles, authority signals, and local search visibility.',
    eyebrow: 'Citations and directories',
    parentPath: '/link-building-services',
    parentLabel: 'Link building services',
    bestFor: 'Local businesses with messy listings, weak local authority, or inconsistent business details.',
    intro: 'Citations are not glamorous, but bad listings confuse local search. The goal is not to submit to every directory. The goal is to clean the important ones and build signals that make the business easier to trust.',
    handles: ['NAP consistency review', 'Priority directory selection', 'Profile cleanup', 'Local authority opportunities', 'Citation gap review'],
    proof: 'Local SEO gains often come from simple trust signals combined with stronger local pages and reviews.',
    related: ['Google Business Profile SEO', 'Backlinks', 'SEO services'],
    cta: 'Send the business name, website, and main city or service area.',
  },
  {
    slug: 'reddit-seo',
    title: 'Use Reddit to support brand discovery and AI search visibility.',
    seoTitle: 'Reddit SEO Consultant | Brand Visibility, Reddit Research, Forum Mentions, AI Search Retrieval and Search Demand Support | Zechariah Tokar',
    metaDescription: 'Reddit SEO help for search visibility, brand mentions, buyer research, AI visibility, and useful discussion-led content.',
    eyebrow: 'Reddit SEO',
    parentPath: '/ai-seo-consultant-israel',
    parentLabel: 'AI SEO',
    bestFor: 'Brands where Reddit threads influence Google results, AI answers, or buyer trust.',
    intro: 'Reddit now shows up in Google results and AI research paths. The useful play is not spam. It is finding the right discussions, understanding objections, and building content or participation that answers real buyer questions.',
    handles: ['Relevant subreddit research', 'Buyer-objection mapping', 'Reddit SERP review', 'Discussion-led content ideas', 'Brand mention opportunities'],
    proof: 'The current SEO system already uses Reddit research for content gaps, AI visibility, and search-aware distribution.',
    related: ['Reddit marketing services', 'Reddit marketing expert', 'Reddit posting service', 'AI SEO / GEO'],
    cta: 'Send the brand and the topic where Reddit is already influencing buyers.',
  },
  {
    slug: 'reddit-marketing-services',
    title: 'Reddit marketing services for brands that need trust, not spam.',
    seoTitle: 'Reddit Marketing Services | Reddit Strategy, Subreddit Research, Buyer Objection Mapping and Search Visibility Support | Zechariah Tokar',
    metaDescription: 'Reddit marketing services for brands that need subreddit research, useful posting ideas, buyer-objection mapping, and search visibility support.',
    eyebrow: 'Reddit marketing services',
    visual: 'redditMarketing',
    parentPath: '/reddit-seo',
    parentLabel: 'Reddit SEO',
    bestFor: 'Brands where buyers already use Reddit to compare options, check trust, or look for real user language.',
    intro: 'This work starts with the community, not the post. I look for the threads where buyers already ask hard questions, compare options, complain about bad advice, or ask strangers for proof. If the topic fits, I turn that research into useful post angles, comment guidance, and website improvements that make the next click more useful.',
    fit: 'This is a good fit when prospects already mention Reddit during sales calls, when a search result includes forum threads, or when your team needs cleaner buyer language before building another service page. Sometimes the right answer is to publish. Sometimes the right answer is to fix the page first and wait.',
    handleTitle: 'Find the conversations worth acting on.',
    handleIntro: 'I turn Reddit threads into a practical plan: what people are asking, what they distrust, what can be answered on-site, and what is safe to say in the community.',
    handles: ['Thread research and repeated objections', 'Post ideas that fit the community', 'Comment guidance before anyone replies', 'Landing-page alignment', 'Search result review'],
    avoids: ['Fake upvote packages', 'Spammy brand mentions', 'Posting in communities that do not fit', 'Volume campaigns that look automated'],
    proof: 'The goal is simple: use Reddit to learn what buyers actually need, then send them to a page that answers it better than the thread did.',
    related: ['Reddit SEO', 'Reddit marketing expert', 'Reddit posting service', 'How to market on Reddit without getting banned', 'How to find subreddits for marketing', 'AI SEO / GEO'],
    cta: 'Send the brand, site, and the Reddit topic you want to test first.',
  },
  {
    slug: 'reddit-marketing-expert',
    title: 'Hire a Reddit marketing expert before you post in the wrong place.',
    seoTitle: 'Reddit Marketing Expert | Reddit Consultant for Subreddit Strategy, Risk Review, Search Visibility and Brand Trust | Zechariah Tokar',
    metaDescription: 'Hire a Reddit marketing expert for subreddit strategy, risk review, buyer research, search visibility, and practical Reddit campaign planning.',
    eyebrow: 'Reddit marketing expert',
    visual: 'redditExpert',
    parentPath: '/reddit-seo',
    parentLabel: 'Reddit SEO',
    bestFor: 'Founders, marketers, and SEO teams that need a second opinion before Reddit becomes a public mistake.',
    intro: 'The useful part of a Reddit consult is usually the pause before posting. I look at the communities, the old threads, the search results, and the way people talk when they are not being sold to. Then I tell you where the brand can participate, where it should stay quiet, and what needs to change on the site before anyone clicks through.',
    fit: 'This fits when a competitor keeps showing up in discussions, when your team is nervous about backlash, or when you need a second opinion before a campaign goes public. The advice has to respect the community first.',
    handleTitle: 'Get a clear call on what to do before you post.',
    handleIntro: 'I review the Reddit landscape, flag the places where the brand could get hit, and give you the practical next move without turning it into a social media calendar.',
    handles: ['Opportunity review', 'Community fit checks', 'Competitor thread research', 'Risk flags', 'Plain next-step advice'],
    avoids: ['Generic social media calendars', 'Scripted replies that ignore the thread', 'Advice built only around karma', 'Promising results Reddit cannot guarantee'],
    proof: 'The point is to make Reddit useful without turning your brand into the thing people complain about.',
    related: ['Reddit SEO', 'Reddit marketing services', 'Reddit posting service', 'How to market on Reddit without getting banned', 'Why Reddit posts get removed', 'AI SEO / GEO'],
    cta: 'Send the site and the Reddit move you are considering.',
  },
  {
    slug: 'reddit-posting-service',
    title: 'A Reddit posting service that starts with whether posting is smart.',
    seoTitle: 'Reddit Posting Service | Reddit Post Writing, Review, Publishing Support and Search-Aware Community Content | Zechariah Tokar',
    metaDescription: 'Reddit posting service for careful post planning, native writing, review, publishing support, and search-aware community content.',
    eyebrow: 'Reddit posting service',
    visual: 'redditPosting',
    parentPath: '/reddit-seo',
    parentLabel: 'Reddit SEO',
    bestFor: 'Brands that need Reddit posts planned and reviewed carefully before anything public goes live.',
    intro: 'Most posting services start with a draft. I start with the question that matters more: should this be posted at all? I check the subreddit, the thread history, the likely reaction, and the page you want people to visit if they click.',
    fit: 'If posting makes sense, I help shape the title, body, comment plan, and link so the post reads like it belongs. If the idea is too promotional, too thin, or pointed at the wrong page, I will say that before it goes live.',
    handleTitle: 'Shape the post before it becomes a problem.',
    handleIntro: 'I help turn a rough idea into a Reddit-native post, then check the subreddit fit, the link destination, and the likely objections before anything goes public.',
    handles: ['Post angle selection', 'Title and body writing', 'Subreddit fit checks', 'Pre-publish review', 'Landing-page alignment'],
    avoids: ['Bulk posting', 'Fake accounts or fake engagement', 'Thin promotional posts', 'Link drops'],
    proof: 'The post should help the reader first. The business benefit comes from earning the click, not forcing it.',
    related: ['Reddit SEO', 'Reddit marketing services', 'Reddit marketing expert', 'Why Reddit posts get removed', 'How to market on Reddit without getting banned', 'Content marketing for SEO'],
    cta: 'Send the draft idea, subreddit, and page you want the post to support.',
  },
  {
    slug: 'youtube-seo',
    title: 'Turn videos into searchable assets buyers can actually find.',
    seoTitle: 'YouTube SEO Consultant | Video Titles, Topic Strategy, Descriptions, Search Packaging and AI Visibility for SEO Content | Zechariah Tokar',
    metaDescription: 'YouTube SEO help for video topics, titles, descriptions, search intent, internal links, and Google video visibility.',
    eyebrow: 'YouTube SEO',
    parentPath: '/content-marketing-for-seo',
    parentLabel: 'Content marketing for SEO',
    bestFor: 'Channels or businesses that already make videos but need clearer search packaging.',
    intro: 'YouTube SEO starts before upload. The topic, title, thumbnail promise, description, chapters, and page support all need to match what people search and what the video actually answers.',
    handles: ['Video topic research', 'Title and description cleanup', 'Chapter and entity recommendations', 'Google video SERP checks', 'Blog or service-page support ideas'],
    proof: 'Zechariah publishes SEO videos and uses YouTube as part of the broader search and AI visibility system.',
    related: ['SEO writing', 'AI SEO / GEO', 'SEO social posting'],
    cta: 'Send the channel or video list and the topic you want to be found for.',
  },
  {
    slug: 'programmatic-seo',
    title: 'Build scalable SEO pages that are useful enough to rank.',
    seoTitle: 'Programmatic SEO Consultant | Useful Template Pages, Internal Linking, Indexation Control, Location Pages and Scalable SEO Systems | Zechariah Tokar',
    metaDescription: 'Programmatic SEO consulting for useful template pages, internal linking, indexation, data structure, and scalable search pages.',
    eyebrow: 'Programmatic SEO',
    parentPath: '/ai-seo-consultant-israel',
    parentLabel: 'AI SEO',
    bestFor: 'Companies with real data, locations, categories, products, integrations, or use cases that can support useful page templates.',
    intro: 'Programmatic SEO only works when the page type deserves to exist. Thin generated pages create risk. Useful templates answer a repeated buyer question with specific data, internal links, and a clear next step.',
    handles: ['Page-template strategy', 'Indexation risk review', 'Internal link architecture', 'Data field recommendations', 'Pilot page batch planning'],
    proof: 'The same authority architecture behind B2B and local SEO applies to scalable page systems.',
    related: ['Technical SEO audit', 'AI SEO / GEO', 'B2B SEO'],
    cta: 'Send the idea, data source, and one example page you want to scale.',
  },
  {
    slug: 'seo-consult',
    title: 'Get a clear SEO plan before spending more time or budget.',
    seoTitle: 'SEO Consult | Freelance SEO Consultant for Site Reviews, Priority Roadmaps, Technical Direction and Content Decisions | Zechariah Tokar',
    metaDescription: 'SEO consults for audits, strategy, second opinions, content plans, technical questions, and clear SEO priorities.',
    eyebrow: 'SEO consult',
    parentPath: '/seoconsulting',
    parentLabel: 'SEO consulting',
    bestFor: 'Founders and marketers who need direction before committing to a bigger SEO project.',
    intro: 'A consult is useful when you are stuck between too many SEO tasks. The goal is to decide what matters first, what can wait, and what is probably not worth paying for right now.',
    handles: ['Quick site review', 'GSC and keyword priority review', 'Content or technical second opinion', '90-day priority outline', 'Vendor or freelancer scope review'],
    proof: 'Clients repeatedly mention clear explanations, practical strategy, and honest prioritization in reviews.',
    related: ['Technical SEO audit', 'B2B SEO', 'SEO services'],
    cta: 'Send the site and the decision you are trying to make.',
  },
  {
    slug: 'press-release-seo',
    title: 'Use press releases to support brand search and authority.',
    seoTitle: 'Press Release SEO | PR Mentions, Brand Search Visibility, Authority Building, Third-Party Signals and AI Search Support | Zechariah Tokar',
    metaDescription: 'Press release SEO help for brand search, authority building, third-party mentions, AI visibility, and reputation support.',
    eyebrow: 'Press release SEO',
    parentPath: '/link-building-services',
    parentLabel: 'Link building services',
    bestFor: 'Brands that need credible third-party surfaces to support search, reputation, and AI visibility.',
    intro: 'A press release should not be random noise. It should support a real entity signal: who you are, what you do, why the update matters, and where buyers or AI systems can verify the brand.',
    handles: ['News angle review', 'Entity and brand wording', 'Distribution fit review', 'Anchor and mention planning', 'Follow-up authority opportunities'],
    proof: 'Zechariah has public third-party mentions around SEO consulting, AI search, Wharton background, and Semrush certifications.',
    related: ['Backlinks', 'AI SEO / GEO', 'SEO reputation management'],
    cta: 'Send the announcement idea and the business goal behind it.',
  },
  {
    slug: 'blog-content-seo',
    title: 'Publish blog content that supports rankings, trust, and leads.',
    seoTitle: 'Blog Content SEO | SEO Writing, Content Refreshes, BOFU Articles, Internal Links and Search-Led Topic Planning | Zechariah Tokar',
    metaDescription: 'Blog content SEO help for article strategy, content refreshes, BOFU posts, internal links, and search-focused writing.',
    eyebrow: 'Blog content SEO',
    parentPath: '/content-marketing-for-seo',
    parentLabel: 'Content marketing for SEO',
    bestFor: 'Companies with blog content that should support service pages, comparisons, and buyer research.',
    intro: 'Blog SEO should not mean publishing more words. A useful article answers a real search problem, supports a money page, and gives buyers a reason to trust the business before they contact you.',
    handles: ['Content refresh review', 'BOFU article planning', 'Internal link recommendations', 'SERP and Reddit research', 'Title and meta cleanup'],
    proof: 'The current site already has indexed B2B, AI search, cybersecurity, SaaS, and content marketing articles.',
    related: ['SEO writing', 'B2B SEO', 'AI SEO / GEO'],
    cta: 'Send the blog URL or keyword cluster you want to improve.',
  },
];

export const REDDIT_SUPPORT_PAGES: SupportPage[] = [
  {
    slug: 'how-to-market-on-reddit-without-getting-banned',
    title: 'How to market on Reddit without getting banned.',
    seoTitle: 'How to Market on Reddit Without Getting Banned | Safer Reddit Marketing, Subreddit Rules, Account Trust and Post Planning',
    metaDescription: 'Learn how to market on Reddit without getting banned by checking subreddit fit, account trust, post format, link use, and community expectations first.',
    eyebrow: 'Reddit marketing guide',
    parentPath: '/reddit-marketing-services',
    parentLabel: 'Reddit marketing services',
    intro: 'Do not start with the post. Start with the subreddit, rules, account history, accepted threads, and whether a link actually helps. That is the difference between useful Reddit marketing and a post that gets removed before anyone sees it.',
    sections: [
      {
        heading: 'Check the community before writing',
        body: [
          'Every subreddit has its own tolerance for business participation. Some allow useful links in context. Others remove anything that looks like promotion, even if the advice is decent.',
          'Before posting, read the rules, pinned threads, flair requirements, recent top posts, and recent removed-looking discussions. The goal is to understand what survives in that community, not what would work on LinkedIn.',
        ],
        bullets: ['Read rules and pinned posts', 'Study recent accepted posts', 'Check link and flair requirements', 'Look for how people answer similar questions'],
      },
      {
        heading: 'Build trust before the link',
        body: [
          'Reddit often judges the account and the pattern, not only the sentence you wrote. New accounts, low-karma profiles, repeated links, and sudden brand mentions can trigger filters or downvotes.',
          'A safer path is to answer questions, comment without linking, and only mention the brand or page when it directly helps the thread. Reddit marketing services should reduce risk before they increase posting volume.',
        ],
      },
      {
        heading: 'Use the page only when it answers the thread',
        body: [
          'A landing page should match the exact question being discussed. A homepage link, sales page, or thin blog post usually feels like a drop-in promotion.',
          'If the page does not answer the conversation better than the comment could, fix the page first. A Reddit marketing expert can review the subreddit, post idea, and destination page before anything goes public.',
        ],
      },
      {
        heading: 'When posting needs a second review',
        body: [
          'Get another set of eyes when the subreddit is strict, the account is new, the topic is sensitive, or the post points to a commercial page. A careful Reddit posting service should be comfortable saying not to post yet.',
        ],
      },
    ],
    related: ['Reddit marketing services', 'Reddit marketing expert', 'Reddit posting service', 'How to find subreddits for marketing', 'Why Reddit posts get removed'],
    cta: 'Send the site and subreddit before you post.',
  },
  {
    slug: 'how-to-find-subreddits-for-marketing',
    title: 'How to find subreddits for marketing.',
    seoTitle: 'How to Find Subreddits for Marketing | Reddit Community Research, Buyer Language, Search Visibility and Posting Fit',
    metaDescription: 'Find better subreddits for marketing by looking at active problem threads, rules, moderation patterns, buyer language, and search visibility.',
    eyebrow: 'Reddit audience research',
    parentPath: '/reddit-marketing-services',
    parentLabel: 'Reddit marketing services',
    intro: 'The best subreddit is not always the biggest one. Look for active problem threads, clear rules, fresh comments, and people describing the problem in the same language your buyers use.',
    sections: [
      {
        heading: 'Start with problems, not subreddit size',
        body: [
          'A large subreddit can look attractive and still be useless for marketing. Big communities often have stricter rules, faster downvotes, and less patience for brand participation.',
          'Search for the problem your buyer has, the words they use when they complain, and the alternatives they compare. Reddit marketing services should find the communities where those conversations already happen.',
        ],
      },
      {
        heading: 'Use Google and Reddit together',
        body: [
          'Google can reveal Reddit threads that already rank for buyer questions. Reddit search can show whether the same topic is still active now.',
          'Try searches like site:reddit.com plus the problem, product category, competitor, or exact buyer question. Then sort Reddit by newest and top posts to compare current activity with older search-visible threads.',
        ],
        bullets: ['Search the problem on Google with site:reddit.com', 'Search Reddit by newest and top', 'Check whether threads still get comments', 'Look for repeated complaints and comparisons'],
      },
      {
        heading: 'Read the rules like a marketer who wants to stay',
        body: [
          'A useful subreddit has more than traffic. It has a predictable posting culture. Check whether links are allowed, whether product mentions are common, whether founders participate, and whether posts need a flair, tag, or weekly thread.',
          'If the rules are unclear, study what moderators leave up. If every brand post disappears, the better move may be research, comments, or a page update before posting.',
        ],
      },
      {
        heading: 'Turn subreddit research into better pages',
        body: [
          'The best community research also improves your site. The phrases people repeat on Reddit often expose weak page copy, missing objections, and topics that deserve clearer answers.',
          'A Reddit marketing expert can turn that research into safer post ideas and better landing-page language before the brand enters the discussion.',
        ],
      },
    ],
    related: ['Reddit marketing services', 'Reddit marketing expert', 'How to market on Reddit without getting banned', 'Why Reddit posts get removed'],
    cta: 'Send the product, audience, and site for subreddit research.',
  },
  {
    slug: 'why-reddit-posts-get-removed',
    title: 'Why Reddit posts get removed.',
    seoTitle: 'Why Reddit Posts Get Removed | AutoModerator, Karma, Subreddit Rules, Promotional Tone and Safer Post Review',
    metaDescription: 'Learn why Reddit posts get removed, including AutoModerator filters, account age, karma, missing flair, self-promotion rules, direct links, and poor subreddit fit.',
    eyebrow: 'Reddit posting guide',
    parentPath: '/reddit-posting-service',
    parentLabel: 'Reddit posting service',
    intro: 'A Reddit post can be useful and still get removed. The issue is often the account, format, rules, link pattern, or promotional tone, not just the idea itself.',
    sections: [
      {
        heading: 'Filters may remove the post first',
        body: [
          'AutoModerator and subreddit filters can act before a human moderator reads the post. Common triggers include account age, karma, link domains, missing flair, banned words, repeated submissions, or a format the subreddit does not allow.',
          'That is why a post may disappear quickly or seem visible to the author while getting no real attention.',
        ],
      },
      {
        heading: 'Promotional tone is easy to spot',
        body: [
          'Reddit users are fast at noticing brand language. A direct pitch, generic CTA, repeated brand mention, or link-first post can feel like an ad even when the writer thinks it is helpful.',
          'A good Reddit posting service should shape the post around the reader question first, then decide whether a brand mention or link belongs there at all.',
        ],
        bullets: ['Remove unnecessary links', 'Rewrite the title in community language', 'Add context before mentioning the brand', 'Avoid posting the same angle in multiple subreddits'],
      },
      {
        heading: 'The subreddit may be wrong for the post',
        body: [
          'Some posts fail because they are in the wrong community. A SaaS launch, SEO question, product complaint, or founder lesson may need completely different framing depending on the subreddit.',
          'Before reposting, compare your draft against accepted posts in that exact community. If the tone, format, or subject does not match, rewriting alone may not fix it.',
        ],
      },
      {
        heading: 'Review before reposting',
        body: [
          'Before trying again, check the rules, account trust, flair, title, link destination, and whether the post gives enough value without asking for a click.',
          'If the post supports a commercial page, get a Reddit marketing expert to review it first. Reddit marketing services can also identify whether the better move is a comment, a different subreddit, or a stronger landing page.',
        ],
      },
    ],
    related: ['Reddit posting service', 'Reddit marketing expert', 'Reddit marketing services', 'How to market on Reddit without getting banned', 'How to find subreddits for marketing'],
    cta: 'Send the removed post, subreddit, and target page for review.',
  },
];

const DATA_ECOMMERCE = [
  { date: '1', clicks: 120, impressions: 4000 },
  { date: '2', clicks: 180, impressions: 5500 },
  { date: '3', clicks: 250, impressions: 8000 },
  { date: '4', clicks: 400, impressions: 12000 },
  { date: '5', clicks: 800, impressions: 25000 },
  { date: '6', clicks: 1200, impressions: 45000 },
];

const DATA_LOCAL = [
  { date: '1', clicks: 20, impressions: 500 },
  { date: '2', clicks: 45, impressions: 1200 },
  { date: '3', clicks: 90, impressions: 2800 },
  { date: '4', clicks: 150, impressions: 4000 },
  { date: '5', clicks: 210, impressions: 5500 },
  { date: '6', clicks: 300, impressions: 8000 },
];

const DATA_B2B = [
  { date: '1', clicks: 10, impressions: 1000 },
  { date: '2', clicks: 25, impressions: 2500 },
  { date: '3', clicks: 40, impressions: 3800 },
  { date: '4', clicks: 85, impressions: 6000 },
  { date: '5', clicks: 140, impressions: 9000 },
  { date: '6', clicks: 220, impressions: 15000 },
];

export const CASE_STUDIES: CaseStudy[] = [
  {
    client: 'ZStander',
    metric: '+300%',
    context: 'Increase in Google Sales',
    industry: 'Ecommerce',
    market: 'United States',
    description: 'Optimized collection pages and targeted Google Shopping support around seasonal demand.',
    icon: 'trending_up',
    graphData: DATA_ECOMMERCE,
  },
  {
    client: 'The Behfar Team',
    metric: '#1',
    context: 'Midwood Brooklyn Real Estate',
    industry: 'Real estate',
    market: 'United States',
    description: 'Built local search visibility around high-intent neighborhood real estate searches.',
    icon: 'emoji_events',
    graphData: DATA_LOCAL,
  },
  {
    client: 'North Star Ranch',
    metric: '10+',
    context: 'Leads per month',
    industry: 'Hospitality',
    market: 'United States',
    description: 'Found a micro-wedding keyword gap and built organic visibility without ad spend.',
    icon: 'groups',
    graphData: DATA_B2B,
  },
];

const baseFaqs = [
  {
    question: 'What is the starting price?',
    answer: 'It depends on the service, your site, and how much you want handled. Send your site and I will reply with a clear scope and first step.',
  },
  {
    question: 'Do you work only with Israeli companies?',
    answer: 'No. Zechariah is based in Israel but mainly works with companies targeting English-speaking markets, especially the United States and international buyers.',
  },
];

export const SERVICE_DATA: Record<string, ServiceContent> = {
  services: {
    id: 'seo-services',
    slug: 'seo-services-israel',
    title: 'SEO services in Israel for more rankings, leads, and search visibility.',
    seoTitle: 'SEO Services Israel | Hire Freelance SEO for Technical Audits, SEO Writing, Local SEO, Shopify SEO, AI Search, Backlinks and B2B Growth | Zechariah Tokar',
    metaDescription: 'Hire Zechariah Tokar for SEO writing, audits, AI SEO, backlinks, technical SEO, B2B SEO, and monthly SEO services by hourly quote.',
    subtitle: 'SEO Services Israel',
    primaryKeyword: 'SEO services Israel',
    priceFrom: 'By consultation',
    timeline: '1 week to monthly',
    bestFor: 'Businesses that know the SEO service they need and want a clear starting point.',
    description: 'Choose the SEO help that can move the business first: technical cleanup, service pages, local search, Shopify SEO, content, AI visibility, backlinks, or ongoing support.',
    deliverables: ['SEO writing', 'Technical SEO audit', 'Monthly SEO support', 'Shopify SEO', 'Google Merchant Center', 'Google Business Profile', 'Reddit SEO', 'YouTube SEO'],
    relatedServices: ['SEO writing', 'Audits', 'B2B SEO', 'AI SEO', 'Backlinks'],
    ugcIntro: {
      what: 'A clear menu of freelance SEO services, from one-off writing or audits to ongoing monthly support.',
      why: 'Most buyers want to know what they can hire for, what it starts at, and whether the person can actually do the work.',
      how: 'You send the site and goal. I tell you the best service fit, price range, and first practical step.',
    },
    results: [
      { label: 'Pricing', value: 'By consultation' },
      { label: 'Currency', value: 'USD' },
      { label: 'Work model', value: 'Direct' },
    ],
    caseStudyHighlight: CASE_STUDIES[0],
    process: {
      title: 'How hiring works',
      steps: ['Pick the service area', 'Send the site and goal', 'Get a clear scope', 'Start with the highest-impact work'],
    },
    tools: ['Google Search Console', 'GA4', 'Screaming Frog', 'Reddit research', 'AI workflow tools'],
    pricing: { audit: 'Quoted hourly', management: 'Quoted hourly' },
    features: ['One-off and monthly SEO options', 'Direct senior work', 'Pricing in USD', 'No agency handoff'],
    whyMe: ['Direct access to the person doing the thinking', 'Practical SEO tied to pages, rankings, leads, and sales context'],
    cta: 'Send your site and the service you are considering. I will reply with the cleanest first step.',
    faqs: baseFaqs,
  },
  freelance: {
    id: 'freelance-seo',
    slug: 'freelance-seo-israel',
    title: 'Freelance SEO in Israel for companies that need leads, not reports.',
    seoTitle: 'Freelance SEO Israel | Hire Direct SEO Help for Service Pages, Technical Fixes, Content, Local Search, AI Visibility and Lead Growth | Zechariah Tokar',
    metaDescription: 'Hire Zechariah Tokar for freelance SEO in Israel. Senior SEO done directly, scoped after a quick review of your site.',
    subtitle: 'Freelance SEO Israel',
    primaryKeyword: 'freelance SEO Israel',
    priceFrom: 'By consultation',
    timeline: 'Project or monthly',
    bestFor: 'Founders, marketers, and service businesses that want one accountable SEO operator.',
    description: 'Hire me for practical SEO work without agency layers. I help with writing, audits, technical cleanup, content planning, AI visibility, backlinks, and monthly SEO.',
    deliverables: ['SEO audit', 'Keyword and GSC review', 'Service page rewrites', 'Technical fixes', 'Content strategy', 'Monthly SEO support'],
    relatedServices: ['SEO services', 'B2B SEO', 'Technical SEO', 'AI SEO'],
    ugcIntro: {
      what: 'Hands-on SEO from a freelancer based in Israel, focused on English-speaking markets.',
      why: 'You get faster decisions, clearer priorities, and fewer layers between strategy and execution.',
      how: 'I look at the site, rankings, search intent, and offer, then start with the pages closest to money.',
    },
    results: [
      { label: 'Hourly rate', value: 'By consultation' },
      { label: 'Work style', value: 'Direct' },
      { label: 'Market focus', value: 'US/global' },
    ],
    caseStudyHighlight: CASE_STUDIES[1],
    process: {
      title: 'Freelance SEO process',
      steps: ['Audit what already exists', 'Find the terms closest to buyers', 'Fix weak pages first', 'Build the next service or content pages'],
    },
    tools: ['Google Search Console', 'GA4', 'Screaming Frog', 'Keywords Everywhere', 'Reddit'],
    pricing: { audit: 'Quoted hourly', management: 'Quoted hourly' },
    features: ['SEO writing', 'Technical SEO', 'Monthly SEO', 'AI SEO visibility', 'Backlink strategy'],
    whyMe: ['No account manager relay', 'Plain explanations', 'Search work tied to actual business goals'],
    cta: 'Send the site and tell me what you want SEO to fix first.',
    faqs: baseFaqs,
    deepDive: [
      {
        title: 'What I check first',
        body: "I start with the pages already closest to revenue: service pages, comparison pages, local pages, and any content that has impressions but weak clicks. From there, I check Search Console, crawl basics, titles, page intent, and whether the offer is clear enough for a buyer who doesn't know me yet.",
      },
      {
        title: 'Why direct freelance SEO can work better',
        body: "A lot of SEO slows down because strategy and execution get separated. I keep the first pass direct. If the page needs writing, I write. If the problem is indexing or internal links, I map the fix. If the site needs authority, I point the effort at the pages most likely to bring leads.",
      },
    ],
  },
  b2b: {
    id: 'b2b-seo',
    slug: 'b2b-seo-israel',
    title: 'B2B SEO in Israel that helps buyers find and trust you.',
    seoTitle: 'B2B SEO Israel | SaaS and Service SEO for Buyer Intent Pages, US Market Visibility, BOFU Content and Pipeline Growth | Zechariah Tokar',
    metaDescription: 'B2B SEO in Israel for SaaS, service, and international companies targeting US and English-speaking buyers.',
    subtitle: 'B2B SEO Israel',
    primaryKeyword: 'B2B SEO Israel',
    priceFrom: 'By consultation',
    timeline: 'Monthly or project',
    bestFor: 'B2B, SaaS, service, and tech companies that need buyer-intent pages.',
    description: 'B2B SEO works when it gets close to pipeline: service pages, use cases, comparisons, pricing intent, and content buyers read before they contact you.',
    deliverables: ['B2B keyword map', 'Service page strategy', 'Use case pages', 'Comparison pages', 'Content refreshes', 'Internal linking'],
    relatedServices: ['SEO consulting', 'Content SEO', 'AI SEO'],
    ugcIntro: {
      what: 'SEO for B2B companies that care about qualified leads more than traffic volume.',
      why: 'B2B buyers research before they talk to sales. If the pages are vague, rankings do not help much.',
      how: 'I map the buyer searches, sharpen the offer pages, and build BOFU content around real decision points.',
    },
    results: [
      { label: 'B2B page impressions', value: '1,688' },
      { label: 'Keyword cluster', value: 'B2B SEO Israel' },
      { label: 'Pricing', value: 'By consultation' },
    ],
    caseStudyHighlight: CASE_STUDIES[2],
    process: {
      title: 'B2B SEO process',
      steps: ['Map buyer intent', 'Prioritize money pages', 'Rewrite unclear offers', 'Build BOFU pages', 'Track search and lead signals'],
    },
    tools: ['Google Search Console', 'GA4', 'LinkedIn', 'Reddit research', 'AI search checks'],
    pricing: { audit: 'Quoted hourly', management: 'Quoted hourly' },
    features: ['Pipeline-focused SEO', 'BOFU pages', 'SaaS and service positioning', 'AI-search visibility checks'],
    whyMe: ['I focus on pages that help buyers choose', 'I do not treat B2B SEO as generic blogging'],
    cta: 'Send your B2B site and I will identify the pages closest to revenue.',
    faqs: baseFaqs,
    deepDive: [
      {
        title: 'What I build for B2B companies',
        body: "B2B SEO is not just blog publishing. I look for the searches that happen before someone books a demo, asks for pricing, compares vendors, or tries to understand whether your company fits their market. That usually means service pages, use cases, comparison pages, integrations, and content that sales can actually use.",
      },
      {
        title: 'Where the useful detail comes from',
        body: "Most B2B SEO pages talk about traffic. I care more about whether buyers remember and understand the offer. If Google or an AI answer needs to understand what you do, the page has to name the buyer, the use case, the market, and the proof. That is why I use Search Console data, SERP checks, Reddit language, LinkedIn positioning, and clear related pages together.",
      },
    ],
  },
  consultant: {
    id: 'seo-consulting',
    slug: 'seoconsulting',
    title: 'SEO consulting in Israel for clearer priorities and faster wins.',
    seoTitle: 'SEO Consultant Israel | Strategy, Technical Audits, SEO Roadmaps, Content Priorities, AI Visibility and Execution Guidance | Zechariah Tokar',
    metaDescription: 'SEO consultant in Israel for audits, strategy, roadmaps, technical SEO, content planning, and AI visibility.',
    subtitle: 'SEO Consultant Israel',
    primaryKeyword: 'SEO consultant Israel',
    priceFrom: 'By consultation',
    timeline: 'Audit or advisory',
    bestFor: 'Teams that can execute but need sharper SEO direction.',
    description: 'Use consulting when you need the strategy, diagnosis, and roadmap, but your team will handle some or all execution.',
    deliverables: ['SEO audit', '90-day roadmap', 'Keyword priorities', 'Content brief review', 'Technical review', 'Monthly advisory'],
    relatedServices: ['Technical SEO audit', 'B2B SEO', 'Content SEO'],
    ugcIntro: {
      what: 'Senior SEO direction without committing to a large monthly package.',
      why: 'Most teams do not need more tasks. They need the right order of operations.',
      how: 'I review the site, GSC, competitors, and current pages, then give clear priorities your team can act on.',
    },
    results: [
      { label: 'Pricing', value: 'By consultation' },
      { label: 'Format', value: 'Roadmap' },
      { label: 'Best use', value: 'Clarity' },
    ],
    caseStudyHighlight: CASE_STUDIES[0],
    process: {
      title: 'Consulting process',
      steps: ['Review the site and GSC', 'Identify highest-leverage fixes', 'Map priority pages', 'Give a direct action plan'],
    },
    tools: ['Google Search Console', 'GA4', 'Screaming Frog', 'SERP review'],
    pricing: { audit: 'Quoted hourly', management: 'Custom advisory' },
    features: ['SEO roadmap', 'Technical and content priorities', 'Direct feedback', 'Execution guidance'],
    whyMe: ['Clear priorities instead of a bloated report', 'Useful for founders, marketers, and small teams'],
    cta: 'Send the site and I will tell you if consulting is the right fit.',
    faqs: baseFaqs,
    deepDive: [
      {
        title: 'What a consult is useful for',
        body: "A consult helps when you have too many possible SEO tasks and no clear order. I can look at the site, Search Console, current pages, and competitors, then tell you what I would fix first. Sometimes that is a technical issue. Sometimes the bigger problem is that the page does not say anything useful enough to win the click.",
      },
      {
        title: 'What you leave with',
        body: "The output should be practical. I do not want you stuck with a giant audit nobody opens again. You should know the first few pages to fix, what to write next, what not to waste money on, and whether you need ongoing SEO or just a small focused scope.",
      },
    ],
  },
  content: {
    id: 'content-seo',
    slug: 'content-marketing-for-seo',
    title: 'SEO writing services for pages that rank, explain, and convert.',
    seoTitle: 'SEO Writing Services | Content Marketing for SEO, BOFU Pages, Service Page Copy, Content Refreshes and Lead-Focused Search Copy | Zechariah Tokar',
    metaDescription: 'SEO writing services for BOFU pages, service pages, content refreshes, SEO briefs, and search-focused content by hourly quote.',
    subtitle: 'SEO Writing Services',
    primaryKeyword: 'SEO writing services',
    priceFrom: 'By consultation',
    timeline: 'Per page or batch',
    bestFor: 'Companies that need pages with search intent, proof, and a conversion path.',
    description: 'SEO writing is not blog volume. I write or rebuild pages around buyer intent, search language, proof, and a clear next step.',
    deliverables: ['Service pages', 'BOFU articles', 'Content refreshes', 'SEO briefs', 'Internal link suggestions', 'Title and meta updates'],
    relatedServices: ['B2B SEO', 'SEO services', 'AI SEO'],
    ugcIntro: {
      what: 'SEO writing for service pages, BOFU content, and refreshes.',
      why: 'A page can rank and still fail if the offer is unclear or the copy does not help someone choose.',
      how: 'I map the search intent, compare the SERP, add useful information gain, and write the page around the decision.',
    },
    results: [
      { label: 'Pricing', value: 'By consultation' },
      { label: 'Format', value: 'Page work' },
      { label: 'Focus', value: 'BOFU' },
    ],
    caseStudyHighlight: CASE_STUDIES[2],
    process: {
      title: 'SEO writing process',
      steps: ['Check the query and SERP', 'Choose the page angle', 'Write for clarity and conversion', 'Add title, meta, and links'],
    },
    tools: ['Google Search Console', 'SERP research', 'Reddit research', 'AI-assisted outlining'],
    pricing: { audit: 'Quoted hourly', management: 'Custom batches' },
    features: ['BOFU pages', 'Service pages', 'Refreshes', 'SEO briefs', 'Conversion-focused copy'],
    whyMe: ['I write for buyers, not just keyword density', 'Pages stay clear, short, and useful'],
    cta: 'Send the page or keyword you want to improve.',
    faqs: baseFaqs,
    deepDive: [
      {
        title: 'How I decide what to write',
        body: "I do not start with a content calendar. I start with the search result, the page that should make money, and the questions buyers ask before they trust the offer. A good SEO article should support a service page, answer a real decision, or give Google a clearer reason to understand the brand.",
      },
      {
        title: 'What makes the copy different',
        body: "Most SEO writing sounds interchangeable. I try to put the useful difference near the top: the market, the buyer, the proof, the tools, and the reason this page should exist. That is also how I think about AI search. The page needs enough specific information for a model or a buyer to retrieve the brand for the right reason.",
      },
    ],
  },
  ai: {
    id: 'ai-seo',
    slug: 'ai-seo-consultant-israel',
    title: 'AI SEO consulting for brands that want to be found and recommended.',
    seoTitle: 'AI SEO Consultant Israel | GEO, AI Search Visibility, ChatGPT and Perplexity Retrieval, Reddit Signals and Brand Clarity | Zechariah Tokar',
    metaDescription: 'AI SEO consultant in Israel for GEO, AI visibility, ChatGPT and Perplexity recommendation checks, and automation-assisted SEO.',
    subtitle: 'AI SEO Consultant Israel',
    primaryKeyword: 'AI SEO freelancer',
    priceFrom: 'By consultation',
    timeline: 'Audit or monthly',
    bestFor: 'Brands that want to understand how AI search changes discovery.',
    description: 'AI SEO is not mass-producing generic content. It is making the brand clearer across Google, AI answers, Reddit, reviews, and third-party surfaces.',
    deliverables: ['AI visibility check', 'Brand retrieval review', 'GEO content plan', 'Reddit and forum surface review', 'Automation workflow ideas', 'Entity cleanup'],
    relatedServices: ['SEO consulting', 'Content SEO', 'Backlinks'],
    ugcIntro: {
      what: 'A practical look at how your brand appears in AI-assisted search and recommendation journeys.',
      why: 'Buyers increasingly ask AI who to hire, then Google the names they get back.',
      how: 'I test visibility, find weak entity signals, and build pages or third-party mentions that make the brand easier to retrieve.',
    },
    results: [
      { label: 'Pricing', value: 'By consultation' },
      { label: 'Surfaces', value: 'Google + AI' },
      { label: 'Focus', value: 'Retrieval' },
    ],
    caseStudyHighlight: CASE_STUDIES[0],
    process: {
      title: 'AI SEO process',
      steps: ['Check current AI visibility', 'Map missing entity signals', 'Find trusted surfaces', 'Build content and mentions that clarify the brand'],
    },
    tools: ['ChatGPT checks', 'Perplexity checks', 'Google Search Console', 'Reddit research', 'Automation tools'],
    pricing: { audit: 'Quoted hourly', management: 'Quoted hourly' },
    features: ['GEO visibility', 'AI recommendation checks', 'Brand/entity clarity', 'Automation-assisted SEO'],
    whyMe: ['I treat AI SEO as brand retrieval, not spam content', 'I connect AI visibility with regular Google visibility'],
    cta: 'Send the brand and site. I will check what AI and Google understand about it.',
    faqs: baseFaqs,
    deepDive: [
      {
        title: 'What I mean by AI SEO',
        body: "AI SEO is not publishing a pile of generated posts. I look at whether Google, ChatGPT, Perplexity, Reddit, YouTube, and third-party pages describe the brand clearly. If the brand is hard to understand, it is hard to recommend. That is the problem I try to fix.",
      },
      {
        title: 'What I check',
        body: "I test what AI systems say about the company, then compare that with Google results, Search Console data, internal pages, and outside mentions. The work can include better service pages, clearer entity signals, Reddit research, YouTube packaging, backlinks, or simple cleanup of confusing brand language.",
      },
    ],
  },
  technical: {
    id: 'technical-seo-audit',
    slug: 'technical-seo-audit',
    title: 'Technical SEO audit that shows what to fix first.',
    seoTitle: 'Technical SEO Audit | Google Search Console Cleanup, Indexing Fixes, Crawl Issues, Metadata, Schema and Site Structure | Zechariah Tokar',
    metaDescription: 'Technical SEO audit for Google Search Console, indexing, crawl issues, site structure, metadata, schema, and practical quick wins by hourly quote.',
    subtitle: 'Technical SEO Audit',
    primaryKeyword: 'technical SEO audit',
    priceFrom: 'By consultation',
    timeline: 'Usually 1 week',
    bestFor: 'Sites with ranking, indexing, traffic, or messy technical issues.',
    description: 'A technical audit should tell you what to fix first, not bury you in a giant PDF. I focus on crawlability, indexation, metadata, page structure, and quick wins.',
    deliverables: ['GSC review', 'Indexing checks', 'Metadata issues', 'Site structure review', 'Schema recommendations', 'Priority fix list'],
    relatedServices: ['SEO consulting', 'SEO services', 'B2B SEO'],
    ugcIntro: {
      what: 'A practical audit of the technical issues stopping pages from performing.',
      why: 'Weak indexation, duplicate signals, poor structure, and unclear metadata can waste good content.',
      how: 'I check GSC, crawl the site, review priority templates, and return a short fix list in the right order.',
    },
    results: [
      { label: 'Pricing', value: 'By consultation' },
      { label: 'Output', value: 'Fix list' },
      { label: 'Focus', value: 'GSC' },
    ],
    caseStudyHighlight: CASE_STUDIES[1],
    process: {
      title: 'Audit process',
      steps: ['Review GSC', 'Crawl the site', 'Check indexation and templates', 'Prioritize fixes by impact'],
    },
    tools: ['Google Search Console', 'Screaming Frog', 'GA4', 'PageSpeed Insights'],
    pricing: { audit: 'Quoted hourly', management: 'Custom fixes' },
    features: ['GSC cleanup', 'Indexation checks', 'Metadata review', 'Technical priority list'],
    whyMe: ['Short practical recommendations', 'Focus on fixes that affect search visibility'],
    cta: 'Send your site and I will check where technical SEO is blocking growth.',
    faqs: baseFaqs,
  },
  links: {
    id: 'link-building',
    slug: 'link-building-services',
    title: 'Link building services that support pages worth ranking.',
    seoTitle: 'Link Building Services | SEO Backlinks, Authority Building, PR Mentions, Citations, Third-Party Visibility and Trust Signals | Zechariah Tokar',
    metaDescription: 'Link building services for SEO backlinks, authority building, mentions, citations, and third-party visibility by hourly quote.',
    subtitle: 'Link Building Services',
    primaryKeyword: 'SEO backlinks',
    priceFrom: 'By consultation',
    timeline: 'Monthly or project',
    bestFor: 'Sites that already have decent pages but need more authority and trust signals.',
    description: 'Backlinks should support a real search strategy. I focus on relevant mentions, credible profiles, citations, and surfaces that help buyers and search engines understand the brand.',
    deliverables: ['Authority review', 'Backlink gap check', 'Citation opportunities', 'Profile cleanup', 'PR mention ideas', 'Third-party surface plan'],
    relatedServices: ['AI SEO', 'SEO consulting', 'B2B SEO'],
    ugcIntro: {
      what: 'Authority building through relevant links, mentions, profiles, and third-party surfaces.',
      why: 'A good page still needs trust. Bad links can waste money or create risk.',
      how: 'I review the current link profile, find relevant opportunities, and prioritize quality over volume.',
    },
    results: [
      { label: 'Pricing', value: 'By consultation' },
      { label: 'Focus', value: 'Authority' },
      { label: 'Approach', value: 'Relevant' },
    ],
    caseStudyHighlight: CASE_STUDIES[0],
    process: {
      title: 'Authority process',
      steps: ['Review current authority', 'Compare competitors', 'Find relevant surfaces', 'Build links and mentions around priority pages'],
    },
    tools: ['Moz', 'Google Search', 'Reddit research', 'Directory review'],
    pricing: { audit: 'Quoted hourly', management: 'Quoted hourly' },
    features: ['Backlink gap review', 'Relevant citations', 'Authority planning', 'Third-party visibility'],
    whyMe: ['No link spam promises', 'Authority work tied to pages that matter'],
    cta: 'Send the page you want to strengthen.',
    faqs: baseFaqs,
  },
  reviews: {
    id: 'reviews-results',
    slug: 'reviews-results',
    title: 'SEO freelancer reviews, results, and proof before you hire.',
    seoTitle: 'SEO Freelancer Reviews | Zechariah Tokar Results, Client Feedback, SEO Outcomes, Local SEO Wins and Public Profile Proof | Zechariah Tokar',
    metaDescription: 'Read selected SEO freelancer reviews and results for Zechariah Tokar, including SEO wins across ecommerce, local services, and B2B.',
    subtitle: 'Reviews and Results',
    primaryKeyword: 'SEO freelancer reviews',
    priceFrom: 'By consultation',
    timeline: 'Proof hub',
    bestFor: 'People who want to vet Zechariah before hiring.',
    description: 'Before you hire anyone for SEO, check what clients say and what kind of results the work has produced.',
    deliverables: ['Verified review snippets', 'Selected results', 'Service fit notes', 'Links to public profiles'],
    relatedServices: ['Freelance SEO', 'SEO services', 'B2B SEO'],
    ugcIntro: {
      what: 'A compact proof hub with reviews, selected outcomes, and public places to vet my thinking.',
      why: 'SEO is easy to overclaim. You should be able to check the person before you hire.',
      how: 'Read the review snippets, scan selected results, then use LinkedIn, YouTube, or Reddit to judge the fit.',
    },
    results: [
      { label: 'Ecommerce', value: '+300%' },
      { label: 'Local SEO', value: '#1' },
      { label: 'Pricing', value: 'By consultation' },
    ],
    caseStudyHighlight: CASE_STUDIES[2],
    process: {
      title: 'How to vet me',
      steps: ['Read review snippets', 'Check selected outcomes', 'Review public thinking', 'Send the site if there is a fit'],
    },
    tools: ['LinkedIn', 'YouTube', 'Reddit', 'Google Search Console'],
    pricing: { audit: 'Quoted hourly', management: 'Quoted hourly' },
    features: ['Reviews', 'Selected results', 'Public profiles', 'Direct hire CTA'],
    whyMe: ['You can judge the proof before reaching out', 'The site gives you the service menu and pricing upfront'],
    cta: 'If the proof fits what you need, send the site and service area.',
    faqs: baseFaqs,
  },
};

export const SERVICES_LIST = Object.entries(SERVICE_DATA).map(([key, data]) => ({
  key,
  ...data,
}));

export const CLIENT_LOGOS = [
  { name: 'JLUXURY', style: 'font-display font-bold text-2xl tracking-widest' },
  { name: 'Whitsunday', style: 'font-display italic text-2xl' },
  { name: 'ADORNA', style: 'font-sans font-bold text-xl tracking-[0.3em] border-2 border-current px-2 py-1' },
  { name: 'Pink Orchid', style: 'font-display italic text-2xl' },
  { name: 'NORTH STAR RANCH', style: 'font-sans font-bold text-sm tracking-widest leading-tight text-center' },
];







